disabled_rules:
  - trailing_whitespace
  - todo
  - line_length

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_imports
  - contains_over_first_not_nil
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_string
  - explicit_type_interface
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - unused_import

included:
  - TheWall

excluded:
  - TheWall/TheWallExtension/Resources
  - TheWallTests
  - TheWallUITests
  - build
  - DerivedData

identifier_name:
  min_length: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - db

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 600
  error: 800

type_body_length:
  warning: 300
  error: 400

nesting:
  type_level: 2
  statement_level: 4

cyclomatic_complexity:
  warning: 10
  error: 20

reporter: "xcode"
