declare const styles: {
  readonly altButtonWrapper: string
  readonly altLink: string
  readonly altPopupItem: string
  readonly altPopupList: string
  readonly altPopupMenu: string
  readonly bgLayer: string
  readonly bgOverlay: string
  readonly bottomBar: string
  readonly bottomShareBar: string
  readonly button: string
  readonly buttonFadeIn: string
  readonly buttonsWrapper: string
  readonly closeButton: string
  readonly container: string
  readonly modalContainer: string
  readonly modalContentWrapper: string
  readonly modalFadeIn: string
  readonly modalMargin: string
  readonly modalWrapper: string
  readonly overlayFadeIn: string
  readonly pillBadge: string
  readonly pillBadgeContainerLeft: string
  readonly pillBadgeContainerRight: string
  readonly proofLink: string
  readonly proofSection: string
  readonly proofText: string
  readonly shieldCircleBg: string
  readonly shieldIcon: string
  readonly visible: string
  readonly warningButton: string
}
export = styles
