import { ManualOverrideFields } from "../../types"

export type ManualAdditionItem = {
  name: string
} & (
  | ManualOverrideFields
  | { _processed: true }
  | (ManualOverrideFields & { _processed: true })
  | (ManualOverrideFields & { urls?: string[] })
  | (ManualOverrideFields & { _processed: true; urls?: string[] })
)

export const manualAdditions: ManualAdditionItem[] = [
  {
    name: "AHAV",
    reasons: ["BDS_PRIO"],
    ws: ["https://www.ahava.com"],
    li: ["https://www.linkedin.com/company/dead-sea-laboratories-ahava"],
    fb: ["https://www.facebook.com/ahavagermany"],
    tw: [""]
  },
  {
    name: "Airbnb",
    reasons: ["BDS_PRESSURE"],
    ws: [
      "https://www.airbnb.com",
      "https://www.airbnb.org",
      "https://www.airbnb.co.in",
      "https://community.withairbnb.com",
      "https://insideairbnb.com"
    ],
    fb: [
      "https://www.facebook.com/AirbnbDeutschland",
      "https://www.facebook.com/AirbnbKualaLumpur",
      "https://www.facebook.com/KLAIRBNBManagement",
      "https://www.facebook.com/airbnboftheday"
    ],
    ig: [
      "https://www.instagram.com/airbnb",
      "https://www.instagram.com/airbnbautomated",
      "https://www.instagram.com/airbnbilegeziyorum",
      "https://www.instagram.com/bnbindubai",
      "https://www.instagram.com/nile_airbnbs",
      "https://www.instagram.com/optimizemyairbnb",
      "https://www.instagram.com/top.airbnb.brasil"
    ],
    gh: ["https://github.com/airbnb"],
    ytp: [
      "https://www.youtube.com/@AirbnbHostTemplate",
      "https://www.youtube.com/@AirbnbMaxProfit",
      "https://www.youtube.com/@AirbnbRentalEmpire",
      "https://www.youtube.com/@AirbnbUncovered",
      "https://www.youtube.com/@JorgeContrerasyoutube",
      "https://www.youtube.com/@OptimizeMyAirbnb",
      "https://www.youtube.com/@STRSpecialist",
      "https://www.youtube.com/@Silicon.Valley.Airbnb",
      "https://www.youtube.com/@ThanksForVisiting",
      "https://www.youtube.com/@airbnb",
      "https://www.youtube.com/@airbnbabcs2050",
      "https://www.youtube.com/@airbnbreviewer",
      "https://www.youtube.com/@airbnbuniversity9745",
      "https://www.youtube.com/@top10airbnb",
      "https://www.youtube.com/airbnb"
    ],
    tt: [
      "https://www.tiktok.com/@airbnb",
      "https://www.tiktok.com/@airbnbheaven",
      "https://www.tiktok.com/@airbnbmastery101",
      "https://www.tiktok.com/@airbndguide",
      "https://www.tiktok.com/@diani_ukunda_airbnb_host",
      "https://www.tiktok.com/@ernsuperhost",
      "https://www.tiktok.com/@findyourgetaway",
      "https://www.tiktok.com/@giulliannasairbnb_miami",
      "https://www.tiktok.com/@halliemaarie",
      "https://www.tiktok.com/@jooodoairbnb",
      "https://www.tiktok.com/@mountainmamacabins",
      "https://www.tiktok.com/@selfbnb"
    ],
    th: [
      "https://www.threads.com/@adamhindleyofficial",
      "https://www.threads.com/@airbnb",
      "https://www.threads.com/@jonnellatkins",
      "https://www.threads.com/@myairbnb.my"
    ],
    urls: [
      "https://apps.apple.com/us/app/airbnb/id401626263",
      "https://chromewebstore.google.com/detail/airbnb-dark-mode/fbanmddmbnpfmkdaclfnecpdganjpimg",
      "https://chromewebstore.google.com/detail/airbnb-no-split-stays/cmkhgldhdejnmbijbjnamnngakonpkpm",
      "https://chromewebstore.google.com/detail/airplus-advanced-options/bdcdjfoindheggeigmgocjlglbphnkdn",
      "https://chromewebstore.google.com/detail/bnb-toolbox-scraper-for-a/aglgekjeoncjfdddoeglnjomllloplcl",
      "https://chromewebstore.google.com/detail/compare-airbnb-side-to-si/jioffghkcmonpgnbjfpnpmamblmijkop",
      "https://chromewebstore.google.com/detail/hichee-airbnbbookingvrbo/ikoocbbcgemiakcmeepjmlgipjeeibon"
    ],
    android_app_ids: ["com.airbnb.android"],
    _processed: true
  },
  {
    name: "Amazon",
    reasons: ["BDS_PRESSURE"],
    ws: [
      "https://www.amazon.com",
      "https://www.aboutamazon.com",
      "https://www.amazon.jobs",
      "https://www.amazon.science",
      "https://www.amazon.com.mx",
      "https://www.amazon.com.au",
      "https://www.amazon.com.br",
      "https://www.amazon.com.sg",
      "https://www.amazon.eg",
      "https://www.amazon.com.sa",
      "https://www.amazon.ae",
      "https://www.amazon.com.bh",
      "https://www.amazon.com.jo",
      "https://www.amazon.com.kw"
    ],
    li: [
      "https://www.linkedin.com/company/amazon",
      "https://www.linkedin.com/showcase/sellwithamazon",
      "https://www.linkedin.com/company/abebooks",
      "https://www.linkedin.com/company/souq-com",
      "https://www.linkedin.com/company/dispatch.ai",
      "https://www.linkedin.com/company/souq-com",
      "https://www.linkedin.com/company/abebooks",
      "https://www.linkedin.com/showcase/sellwithamazon",
      "https://www.linkedin.com/showcase/test---fulfillment-by-amazon",
      "https://www.linkedin.com/company/inltinc",
      "https://www.linkedin.com/company/perceive-io",
      "https://www.linkedin.com/showcase/amazon-launchpad",
      "https://www.linkedin.com/showcase/amazon-clinic",
      "https://www.linkedin.com/company/zappos.com",
      "https://www.linkedin.com/company/lovefilm",
      "https://www.linkedin.com/company/lab126",
      "https://www.linkedin.com/showcase/amazon-associates",
      "https://www.linkedin.com/company/woot-inc.",
      "https://www.linkedin.com/company/curse-inc.",
      "https://www.linkedin.com/company/quidsi-inc.",
      "https://www.linkedin.com/company/graphiq",
      "https://www.linkedin.com/showcase/just-walk-out-technology",
      "https://www.linkedin.com/company/annapurna-labs",
      "https://www.linkedin.com/showcase/amazonadvertising",
      "https://www.linkedin.com/company/imdb-com",
      "https://www.linkedin.com/company/woot-inc.",
      "https://www.linkedin.com/company/curse-inc",
      "https://www.linkedin.com/company/quidsi-inc.",
      "https://www.linkedin.com/company/graphiq",
      "https://www.linkedin.com/showcase/just-walk-out-technology",
      "https://www.linkedin.com/company/annapurna-labs",
      "https://www.linkedin.com/showcase/amazonadvertising",
      "https://www.linkedin.com/company/imdb-com",
      "https://www.linkedin.com/company/a9-com",
      "https://www.linkedin.com/company/sqrrl",
      "https://www.linkedin.com/company/amazon-business",
      "https://www.linkedin.com/company/whole-foods-market",
      "https://www.linkedin.com/company/amazon-music",
      "https://www.linkedin.com/showcase/amazon-careers",
      "https://www.linkedin.com/company/veeqo",
      "https://www.linkedin.com/showcase/amazonfashion",
      "https://www.linkedin.com/showcase/amazon-smart-vehicles",
      "https://www.linkedin.com/company/liquavista",
      "https://www.linkedin.com/showcase/kindle-enterprise",
      "https://www.linkedin.com/company/alexa-internet",
      "https://www.linkedin.com/company/shopbop",
      "https://www.linkedin.com/company/createspace",
      "https://www.linkedin.com/company/audible",
      "https://www.linkedin.com/showcase/transportation-shipping-logistics-at-amazon",
      "https://www.linkedin.com/company/goodreads-com",
      "https://www.linkedin.com/showcase/amazon-pay",
      "https://www.linkedin.com/showcase/amazonleo",
      "https://www.linkedin.com/showcase/amazon-alexa-developers",
      "https://www.linkedin.com/company/ring-labs",
      "https://www.linkedin.com/company/comixology",
      "https://www.linkedin.com/company/primevideoamazonstudios",
      "https://www.linkedin.com/showcase/amazon-ads-partners",
      "https://www.linkedin.com/showcase/amazon-appstore-developers",
      "https://www.linkedin.com/company/amazon-development-center-poland",
      "https://www.linkedin.com/company/brilliance-publishing",
      "https://www.linkedin.com/showcase/amazonscience",
      "https://www.linkedin.com/company/thinkbox-software-inc.",
      "https://www.linkedin.com/company/cloostermans"
    ],
    fb: [
      "https://www.facebook.com/Amazon.comBooks",
      "https://www.facebook.com/AmazonAssociates",
      "https://www.facebook.com/AmazonAustralia",
      "https://www.facebook.com/AmazonDevelopmentCenterRomania",
      "https://www.facebook.com/AmazonJobs",
      "https://www.facebook.com/AmazonMusicDE/?brand_redir=159617907465284",
      "https://www.facebook.com/AmazonUK",
      "https://www.facebook.com/amazon.eg",
      "https://www.facebook.com/amazonae",
      "https://www.facebook.com/amazonksa",
      "https://www.facebook.com/amazonwebservices.de/?brand_redir=153063591397681"
    ],
    ig: [
      "https://www.instagram.com/amazon",
      "https://www.instagram.com/amazonprime",
      "https://www.instagram.com/amazonuk"
    ],
    gh: [
      "https://github.com/amazon-archives",
      "https://github.com/amazon-connect",
      "https://github.com/amazon-far",
      "https://github.com/amazon-science",
      "https://github.com/amazonlinux",
      "https://github.com/amzn",
      "https://github.com/aws",
      "https://github.com/awsdocs",
      "https://github.com/awslabs"
    ],
    ytp: [
      "https://www.youtube.com/user/amazon",
      "https://www.youtube.com/@AmazonAlexa",
      "https://www.youtube.com/@AmazonBrasil",
      "https://www.youtube.com/@AmazonGlobalSellingVietNam",
      "https://www.youtube.com/@AmazonInOfficial",
      "https://www.youtube.com/@AmazonJapanOfficial",
      "https://www.youtube.com/@AmazonNews",
      "https://www.youtube.com/@AmazonScience",
      "https://www.youtube.com/@AmazonSellerUniversity",
      "https://www.youtube.com/@PrimeVideo",
      "https://www.youtube.com/@PrimeVideoES",
      "https://www.youtube.com/@PrimeVideoFR",
      "https://www.youtube.com/@PrimeVideoIN",
      "https://www.youtube.com/@PrimeVideoJP",
      "https://www.youtube.com/@PrimeVideoTR",
      "https://www.youtube.com/@PrimeVideoUK",
      "https://www.youtube.com/@amazon",
      "https://www.youtube.com/@amazonkidsplus",
      "https://www.youtube.com/@amazonmusic",
      "https://www.youtube.com/@insideamazonvideos",
      "https://www.youtube.com/@sellersofamazon",
      "https://www.youtube.com/user/AmazonWebServices/Cloud"
    ],
    tt: [
      "https://www.tiktok.com/@amazon",
      "https://www.tiktok.com/@amazon.fr",
      "https://www.tiktok.com/@amazon_publishing",
      "https://www.tiktok.com/@amazonalexa",
      "https://www.tiktok.com/@amazonbeauty",
      "https://www.tiktok.com/@amazonfashion",
      "https://www.tiktok.com/@amazonhome",
      "https://www.tiktok.com/@amazoninfluencers",
      "https://www.tiktok.com/@amazonlive",
      "https://www.tiktok.com/@amazonmusic",
      "https://www.tiktok.com/@amazonmusiclatin",
      "https://www.tiktok.com/@amazonvenezuela",
      "https://www.tiktok.com/@amazonwebservices",
      "https://www.tiktok.com/@primestudent",
      "https://www.tiktok.com/@primevideofr",
      "https://www.tiktok.com/@primevideopl",
      "https://www.tiktok.com/@primevideose",
      "https://www.tiktok.com/@theamazonbox"
    ],
    th: [
      "https://www.threads.com/@amazon",
      "https://www.threads.com/@amazonkindle",
      "https://www.threads.com/@amazonmgmstudios",
      "https://www.threads.com/@amazonmusic",
      "https://www.threads.com/@amazonprime",
      "https://www.threads.com/@amazonuk",
      "https://www.threads.com/@amazonwebservices"
    ],
    urls: [
      "https://amazonone.aws.com",
      "https://aws.amazon.com",
      "https://finance.yahoo.com/quote/AMZN",
      "https://www.cnbc.com/quotes/AMZN",
      "https://www.forbes.com/companies/amazon",
      "https://www.nasdaq.com/market-activity/stocks/amzn",
      "https://www.pinterest.com/amazon",
      "https://www.primevideo.com/offers/nonprimehomepage/ref=dv_web_force_root",
      "https://apps.apple.com/us/app/amazon-a-to-z/id1413909063",
      "https://apps.apple.com/us/app/amazon-alexa/id944011620",
      "https://apps.apple.com/us/app/amazon-flex/id1454725763",
      "https://apps.apple.com/us/app/amazon-kindle/id302584613",
      "https://apps.apple.com/us/app/amazon-music-songs-podcasts/id510855668",
      "https://apps.apple.com/us/app/amazon-prime-video/id545519333",
      "https://apps.apple.com/us/app/amazon-seller/id794141485",
      "https://apps.apple.com/us/app/amazon-shopping/id297606951",
      "https://chromewebstore.google.com/detail/amazon-q-business/feihpdljijcgnokhfoibicengfiellbp",
      "https://chromewebstore.google.com/detail/ds-amazon-quick-view/jkompbllimaoekaogchhkmkdogpkhojg",
      "https://chromewebstore.google.com/detail/keepa-amazon-price-tracke/neebplgakaahbhdphmkckjjcegoiijjo",
      "https://chromewebstore.google.com/detail/productor-for-merch-by-am/almiakmbepejhcjnfhhjkcfabeepefno",
      "https://chromewebstore.google.com/detail/sendhereplz-amazon-shippi/anpeeogkdbgkhakjldceemkolhggobhd",
      "https://marketplace.visualstudio.com/items?itemName=AmazonEMR.emr-tools",
      "https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2022",
      "https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.amazon-q-vscode",
      "https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode",
      "https://marketplace.visualstudio.com/items?itemName=CDATASOFTWARE.AmazonDynamoDBODBCDriver",
      "https://marketplace.visualstudio.com/items?itemName=CDATASOFTWARE.AmazonRedshiftADO",
      "https://marketplace.visualstudio.com/items?itemName=CDATASOFTWARE.AmazonS3ADONETProvider",
      "https://marketplace.visualstudio.com/items?itemName=CDATASOFTWARE.AmazonSimpleDBADONETProvider",
      "https://marketplace.visualstudio.com/items?itemName=CDATASOFTWARE.AmazonSimpleDBODBCDriver",
      "https://marketplace.visualstudio.com/items?itemName=CDATASOFTWARE.ama1",
      "https://marketplace.visualstudio.com/items?itemName=CDATASOFTWARE.amaz3",
      "https://marketplace.visualstudio.com/items?itemName=KingswaySoft.ssisamazons3",
      "https://marketplace.visualstudio.com/items?itemName=Progress.ddtekredshift",
      "https://marketplace.visualstudio.com/items?itemName=ZappySys.SSISAmazonS3Task",
      "https://marketplace.visualstudio.com/items?itemName=ZappySys.ssis-amazon-redshift-integration-pack",
      "https://marketplace.visualstudio.com/items?itemName=mark-tucker.aws-cli-configure"
    ],
    android_app_ids: [
      "com.amazon.kindle",
      "com.amazon.mShop.android.shopping",
      "com.amazon.mp3",
      "com.amazon.amazonvideo.livingroom",
      "com.amazon.atozm",
      "com.amazon.avod.thirdpartyclient",
      "com.amazon.clouddrive.photos",
      "com.amazon.dee.app",
      "com.amazon.sellermobile.android",
      "com.amazon.storm.lightning.client.aosp",
      "com.amazon.ziggy.android",
      "com.keepa.mobile"
    ],
    _processed: true
  },
  {
    name: "AXA",
    reasons: ["BDS_PRIO"],
    ws: ["https://www.axa.com", "https://www.axa.com.hk"],
    li: [
      "https://www.linkedin.com/company/axa/",
      "https://www.linkedin.com/company/axa-wealth/",
      "https://www.linkedin.com/company/axa-group-operations/",
      "https://www.linkedin.com/company/axa-partners/",
      "https://www.linkedin.com/company/axa-global-re/",
      "https://www.linkedin.com/company/bharti-axa-life-insurance/",
      "https://www.linkedin.com/company/axa-mbask-ojsc/",
      "https://www.linkedin.com/company/axa-investment-managers/",
      "https://www.linkedin.com/company/axa-life-invest/",
      "https://www.linkedin.com/company/architas-multi-manager/",
      "https://www.linkedin.com/company/axa-global-direct/",
      "https://www.linkedin.com/company/axa-uk/",
      "https://www.linkedin.com/showcase/healthanea/",
      "https://www.linkedin.com/showcase/axa-von-herz-zu-herz-e-v/",
      "https://www.linkedin.com/company/axahealth/",
      "https://www.linkedin.com/company/gig-saudi/",
      "https://www.linkedin.com/company/axahongkong/",
      "https://www.linkedin.com/company/axa-corporate-solutions/",
      "https://www.linkedin.com/company/axa-gulf/",
      "https://www.linkedin.com/company/axa-liabilities-managers/",
      "https://www.linkedin.com/company/axa-mps/",
      "https://www.linkedin.com/company/axa-minmetals-assurance/",
      "https://www.linkedin.com/company/axa-france/",
      "https://www.linkedin.com/showcase/axa-research-fund/"
    ],
    fb: [
      "https://www.facebook.com/AXA.de/",
      "https://www.facebook.com/AXAAssuranceMaroc",
      "https://www.facebook.com/axainsurance",
      "https://www.facebook.com/AXAHongKong"
    ],
    tw: ["https://x.com/AXA"],
    ig: [
      "https://www.instagram.com/axa",
      "https://www.instagram.com/axa_global",
      "https://www.instagram.com/axa_egypt",
      "https://www.instagram.com/axahealth",
      "https://www.instagram.com/axa_uk"
    ],
    ytp: [
      "https://www.youtube.com/@AXA",
      "https://www.youtube.com/@AXAIRL",
      "https://www.youtube.com/@AXAGBS",
      "https://www.youtube.com/@AXAHongKongVideos",
      "https://www.youtube.com/@axauk",
      "https://www.youtube.com/@AXAPHofficial",
      "https://www.youtube.com/@AXANICoUK",
      "https://www.youtube.com/@AXAHealth"
    ],
    tt: ["https://www.tiktok.com/@axa.com/"],
    th: ["https://www.threads.com/@axa.com/"],
    android_dev_id: "com.axa",
    android_app_ids: [
      "de.axa.noa",
      "com.rise_world.axa",
      "com.agh.ipmi.prod",
      "com.axaassistance.cardmemberbenefits",
      "ch.swisscharge.axa.sc",
      "com.axabanque.fr"
    ]
  },
  {
    name: "Booking",
    reasons: ["BDS_PRESSURE"],
    ws: ["https://www.booking.com", "https://www.bookingholdings.com"],
    fb: ["https://www.facebook.com/bookingcom", "https://www.facebook.com/planetbooking"],
    ig: [
      "https://www.instagram.com/bookingcom",
      "https://www.instagram.com/bookingcom_br",
      "https://www.instagram.com/bookingcomteam"
    ],
    gh: ["https://github.com/bookingcom"],
    ytp: [
      "https://www.youtube.com/@Workingatbooking",
      "https://www.youtube.com/@bookingcom",
      "https://www.youtube.com/@bookingpartners"
    ],
    tt: ["https://www.tiktok.com/@bookingcom"],
    th: ["https://www.threads.com/@bookingcom"],
    urls: [
      "https://apps.apple.com/us/app/booking-com-hotels-travel/id367003839",
      "https://chromewebstore.google.com/detail/bookingcom-price-tracker/kddajedgmmccjldkcbafjlmcpcgkaodp",
      "https://www.facebook.com/groups/126979691325644",
      "https://www.facebook.com/groups/222971688655831",
      "https://www.facebook.com/groups/professionalhosts"
    ],
    android_app_ids: ["com.booking"],
    _processed: true
  },
  {
    name: "BurgerKing",
    reasons: ["BDS_GRASS"],
    fb: [
      "https://www.facebook.com/bkmalaysia",
      "https://www.facebook.com/BurgerKingArabia",
      "https://www.facebook.com/BurgerKingBarbados",
      "https://www.facebook.com/BurgerKingNZ",
      "https://www.facebook.com/BurgerKingTrinidadTobago",
      "https://www.facebook.com/burgerking",
      "https://www.facebook.com/burgerkinguk"
    ],
    ig: [
      "https://www.instagram.com/burgerking",
      "https://www.instagram.com/burgerking.id",
      "https://www.instagram.com/burgerkingal",
      "https://www.instagram.com/burgerkingarg",
      "https://www.instagram.com/burgerkingbelarus",
      "https://www.instagram.com/burgerkingbr",
      "https://www.instagram.com/burgerkingcol",
      "https://www.instagram.com/burgerkingec",
      "https://www.instagram.com/burgerkinghonduras",
      "https://www.instagram.com/burgerkingksa",
      "https://www.instagram.com/burgerkingkw",
      "https://www.instagram.com/burgerkingmacedoniaofficial",
      "https://www.instagram.com/burgerkingoman",
      "https://www.instagram.com/burgerkingportugal",
      "https://www.instagram.com/burgerkingrd",
      "https://www.instagram.com/burgerkingsg",
      "https://www.instagram.com/burgerkingsl",
      "https://www.instagram.com/burgerkingve",
      "https://www.instagram.com/mybkbarbados"
    ],
    gh: ["https://github.com/search?q=BurgerKing&type=users"],
    ytp: [
      "https://www.youtube.com/@BKArabiaTV",
      "https://www.youtube.com/@BURGERKING",
      "https://www.youtube.com/@BURGERKINGHUNGARY",
      "https://www.youtube.com/@BurgerKingArg",
      "https://www.youtube.com/@BurgerKingBR",
      "https://www.youtube.com/@BurgerKingBrampton",
      "https://www.youtube.com/@BurgerKingDeutschland",
      "https://www.youtube.com/@BurgerKingIndia",
      "https://www.youtube.com/@BurgerKingItalia",
      "https://www.youtube.com/@BurgerKingMN",
      "https://www.youtube.com/@BurgerKingPuertoRico",
      "https://www.youtube.com/@BurgerKingRU",
      "https://www.youtube.com/@BurgerKingSE",
      "https://www.youtube.com/@BurgerKingThailand",
      "https://www.youtube.com/@BurgerKingTurkiye",
      "https://www.youtube.com/@BurgerKing_UK",
      "https://www.youtube.com/@Burgerking-121",
      "https://www.youtube.com/@Burgerking22",
      "https://www.youtube.com/@Burgerkingespana",
      "https://www.youtube.com/@burgerking.indonesia",
      "https://www.youtube.com/@burgerking7337",
      "https://www.youtube.com/@burgerking9821",
      "https://www.youtube.com/@burgerking_nl",
      "https://www.youtube.com/@burgerkingbangladesh7138",
      "https://www.youtube.com/@burgerkingcambodia1954",
      "https://www.youtube.com/@burgerkingcanada6141",
      "https://www.youtube.com/@burgerkingcyprus9712",
      "https://www.youtube.com/@burgerkingfrance2500",
      "https://www.youtube.com/@burgerkingkuwait",
      "https://www.youtube.com/@burgerkingmalaysia5171",
      "https://www.youtube.com/@burgerkingmalta5064",
      "https://www.youtube.com/@burgerkingnassau6313",
      "https://www.youtube.com/@burgerkingnigeria",
      "https://www.youtube.com/@burgerkingph",
      "https://www.youtube.com/@burgerkingportugal3411",
      "https://www.youtube.com/@burgerkingqatar-eq7tj"
    ],
    tt: [
      "https://www.tiktok.com/@burgerking_corso_novara",
      "https://www.tiktok.com/@burgerkingbelux",
      "https://www.tiktok.com/@burgerkingbr",
      "https://www.tiktok.com/@burgerkingbrunei",
      "https://www.tiktok.com/@burgerkingca",
      "https://www.tiktok.com/@burgerkinghungary",
      "https://www.tiktok.com/@burgerkingkorea",
      "https://www.tiktok.com/@burgerkinguae"
    ],
    th: [
      "https://www.threads.com/@burgerking",
      "https://www.threads.com/@burgerking.uzb",
      "https://www.threads.com/@burgerkingbr",
      "https://www.threads.com/@burgerkingfr",
      "https://www.threads.com/@burgerkingmx",
      "https://www.threads.com/@burgerkingph",
      "https://www.threads.com/@burgerkinguk"
    ],
    urls: [
      "https://www.burgerking.com.my",
      "https://www.pavilion-kl.com/store/burger-king",
      "https://apps.apple.com/us/app/%D0%B1%D1%83%D1%80%D0%B3%D0%B5%D1%80-%D0%BA%D0%B8%D0%BD%D0%B3-%D0%B0%D0%BA%D1%86%D0%B8%D0%B8-%D0%B4%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B0/id1257821028",
      "https://apps.apple.com/us/app/burger-king-app/id638323895",
      "https://apps.apple.com/us/app/burger-king-india/id1516627543",
      "https://apps.apple.com/us/app/burger-king-puerto-rico/id1017388456"
    ],
    android_app_ids: [
      "burgerking.id.android",
      "com.burgerkingqatar.android",
      "com.frakton.burgerking",
      "in.burgerking.android",
      "mn.burgerking.delivery"
    ],
    _processed: true
  },
  {
    name: "Caltex",
    reasons: ["BDS_PRIO"],
    ws: ["https://www.caltex.com", "https://caltexlubricants.com"],
    fb: ["https://www.facebook.com/CaltexLubricantsEG", "https://www.facebook.com/CaltexSingapore"],
    tw: ["https://x.com/CaltexSingapore"],
    ig: ["https://www.instagram.com/boycottcaltex"],
    ytp: [
      "https://www.youtube.com/@CaltexBrand",
      "https://www.youtube.com/@CaltexDavao",
      "https://www.youtube.com/@CaltexLubricantsIN",
      "https://www.youtube.com/@CaltexNZ",
      "https://www.youtube.com/@CaltexPakistanOfficial",
      "https://www.youtube.com/@CaltexPronPiyananOil",
      "https://www.youtube.com/@CaltexSriLanka2021",
      "https://www.youtube.com/@Pt.lancarsaktioffice",
      "https://www.youtube.com/@caltex7410",
      "https://www.youtube.com/@caltex_australia",
      "https://www.youtube.com/@caltexbrafordlubricants5906",
      "https://www.youtube.com/@caltexcambodia1379",
      "https://www.youtube.com/@caltexcambodia1971",
      "https://www.youtube.com/@caltexcareers1480",
      "https://www.youtube.com/@caltexdigital7354",
      "https://www.youtube.com/@caltexeasterncape6866",
      "https://www.youtube.com/@caltexglenashley333",
      "https://www.youtube.com/@caltexksa1253",
      "https://www.youtube.com/@caltexlubenar4660",
      "https://www.youtube.com/@caltexlubricantsme",
      "https://www.youtube.com/@caltexnz2571",
      "https://www.youtube.com/@caltexnz5716",
      "https://www.youtube.com/@caltexofficialstoremalaysi5917",
      "https://www.youtube.com/@caltexsouthafrica5590"
    ],
    tt: [
      "https://www.tiktok.com/@caltex.tmn.intan",
      "https://www.tiktok.com/@caltex_emstar",
      "https://www.tiktok.com/@caltexassamkumbang",
      "https://www.tiktok.com/@caltexbachok",
      "https://www.tiktok.com/@caltexmy",
      "https://www.tiktok.com/@caltexsungaitong",
      "https://www.tiktok.com/@caltexthailand",
      "https://www.tiktok.com/@gimtit168"
    ],
    urls: [
      "https://apps.apple.com/us/app/caltex-nz/id1435121311",
      "https://apps.apple.com/us/app/caltex-pakistan/id1239372998",
      "https://apps.apple.com/us/app/caltex-workshop/id1522862138",
      "https://apps.apple.com/us/app/caltexgo-rewards/id1607535654",
      "https://apps.apple.com/us/app/netlube-caltex-australia/id685230181",
      "https://apps.apple.com/us/app/netlube-caltex-new-zealand/id946248618",
      "https://play.google.com/store/apps/developer?id=Chevron+Singapore+Pte+Ltd",
      "https://afsc.org/BoycottChevron"
    ],
    android_app_ids: [
      "com.Caltex.CaltexWorkshop",
      "com.caltex.starcardonline",
      "com.chevron.caltexgo.prod",
      "pk.caltex.chevron"
    ],
    _processed: true
  },
  {
    name: "Carrefour",
    reasons: ["BDS_PRIO"],
    ws: ["https://www.carrefour.com"],
    fb: [
      "https://www.facebook.com/Carrefour.Iraq",
      "https://www.facebook.com/CarrefourGeorgia",
      "https://www.facebook.com/Carrefoursaudi",
      "https://www.facebook.com/carrefour",
      "https://www.facebook.com/carrefouregypt"
    ],
    ig: [
      "https://www.instagram.com/carrefoures",
      "https://www.instagram.com/carrefourfrance",
      "https://www.instagram.com/carrefoursa"
    ],
    gh: ["https://github.com/Carrefour-Group"],
    ytp: [
      "https://www.youtube.com/@C4TVShow",
      "https://www.youtube.com/@CarrefourBE",
      "https://www.youtube.com/@CarrefourEgypt1",
      "https://www.youtube.com/@CarrefourFrance",
      "https://www.youtube.com/@CarrefourItaliaOfficial",
      "https://www.youtube.com/@CarrefourPL",
      "https://www.youtube.com/@CarrefourRomania",
      "https://www.youtube.com/@CarrefourUAE",
      "https://www.youtube.com/@GrupoCarrefourBrasil",
      "https://www.youtube.com/@carrefour",
      "https://www.youtube.com/@carrefour_israel",
      "https://www.youtube.com/@carrefourargentina",
      "https://www.youtube.com/@carrefourbrasil",
      "https://www.youtube.com/@carrefourcuracao",
      "https://www.youtube.com/@carrefourpakistan9493",
      "https://www.youtube.com/@carrefouruganda",
      "https://www.youtube.com/c/CarrefourTunisiehypermarch%C3%A9"
    ],
    tt: [
      "https://www.tiktok.com/@carrefour.egypt",
      "https://www.tiktok.com/@carrefour.israel",
      "https://www.tiktok.com/@carrefour.laval0",
      "https://www.tiktok.com/@carrefour.maurice",
      "https://www.tiktok.com/@carrefour_chalon_sud",
      "https://www.tiktok.com/@carrefour_polynesie",
      "https://www.tiktok.com/@carrefour_rosnysousbois",
      "https://www.tiktok.com/@carrefourargentina",
      "https://www.tiktok.com/@carrefourbh",
      "https://www.tiktok.com/@carrefourbrasil",
      "https://www.tiktok.com/@carrefourci",
      "https://www.tiktok.com/@carrefourfortresswaly",
      "https://www.tiktok.com/@carrefourfrance",
      "https://www.tiktok.com/@carrefourmaroc",
      "https://www.tiktok.com/@carrefourpakistan",
      "https://www.tiktok.com/@carrefourromania",
      "https://www.tiktok.com/@carrefoursakurumsal",
      "https://www.tiktok.com/@carrefoursaudi",
      "https://www.tiktok.com/@carrefourtaiwan",
      "https://www.tiktok.com/@carrefouruae",
      "https://www.tiktok.com/search/user?q=Carrefour"
    ],
    urls: [
      "https://apps.apple.com/us/app/carrefour-argentina/id6472512419",
      "https://apps.apple.com/us/app/carrefour-banco/id1488627762",
      "https://apps.apple.com/us/app/carrefour-destreland-contact/id1487957089",
      "https://apps.apple.com/us/app/carrefour-france/id378305156",
      "https://apps.apple.com/us/app/carrefour-maroc/id1644896168",
      "https://apps.apple.com/us/app/carrefour-martinique/id1436006846",
      "https://apps.apple.com/us/app/carrefour-r%C3%A9union/id1480709890",
      "https://apps.apple.com/us/app/carrefoursa-online-al%C4%B1%C5%9Fveri%C5%9F/id1460593315",
      "https://apps.apple.com/us/app/maf-carrefour-online-shopping/id626805470"
    ],
    android_app_ids: ["com.aswat.carrefouruae", "com.carrefourgu", "mn.io.carrefour"],
    _processed: true
  },
  {
    name: "Chevron",
    reasons: ["BDS_PRIO"],
    ws: [
      "https://www.chevron.com",
      "https://www.chevronlubricants.com",
      "www.cpchem.com",
      "https://chevronfuels.com",
      "https://www.chevronmarineproducts.com"
    ],
    li: [
      "https://www.linkedin.com/showcase/chevron-marine-products",
      "https://www.linkedin.com/company/chevron",
      "https://www.linkedin.com/showcase/chevron-colorado",
      "https://www.linkedin.com/showcase/chevronaustralia",
      "https://www.linkedin.com/showcase/chevronhouston",
      "https://www.linkedin.com/showcase/global-lubricants",
      "https://www.linkedin.com/showcase/chevron-new-energies",
      "https://www.linkedin.com/showcase/chevron-delo",
      "https://www.linkedin.com/showcase/chevron-india",
      "https://www.linkedin.com/showcase/chevron-bangladesh",
      "https://www.linkedin.com/showcase/chevron-israel",
      "https://www.linkedin.com/showcase/chevron-oronite",
      "https://www.linkedin.com/showcase/chevron-marine-products",
      "https://www.linkedin.com/company/noble-energy",
      "https://www.linkedin.com/showcase/chevron-technology-ventures"
    ],
    fb: [
      "https://www.facebook.com/BonifaceChevronStation",
      "https://www.facebook.com/Chevron",
      "https://www.facebook.com/ChevronAdvocacyNetwork",
      "https://www.facebook.com/ChevronFuelsandRenewableSolutions"
    ],
    tw: ["https://x.com/Chevron"],
    ig: ["https://www.instagram.com/chevron"],
    gh: ["https://github.com/ChevronETC"],
    ytp: [
      "https://www.youtube.com/@Chevron",
      "https://www.youtube.com/@ChevronOronite",
      "https://www.youtube.com/@ChevronTVArchive",
      "https://www.youtube.com/@chevron.australia",
      "https://www.youtube.com/@chevronangola6961",
      "https://www.youtube.com/@chevronfederalcreditunion9683",
      "https://www.youtube.com/@chevronfuels",
      "https://www.youtube.com/@chevronlubricants7032",
      "https://www.youtube.com/@chevronmarineproducts",
      "https://www.youtube.com/@chevronpascagoularefinery7857",
      "https://www.youtube.com/@chevronmarineproducts"
    ],
    ytc: ["https://www.youtube.com/channel/UCG7MOSE5VUfvaZocYhyxi4w"],
    tt: ["https://www.tiktok.com/@chevron"],
    th: ["https://www.threads.com/@chevron"],
    urls: [
      "https://apps.apple.com/us/app/chevron/id1450978468",
      "https://chevronadvocacynetwork.com",
      "https://play.google.com/store/apps/dev?id=5536479555375186639",
      "https://www.ecosia.org/search?q=Chevron",
      "https://finance.yahoo.com/quote/CVX/",
      "https://www.cnbc.com/quotes/CVX",
      "https://www.forbes.com/companies/chevron/",
      "https://www.bnm.gov.my/-/chevron-malaysia-limited",
      "https://www.marketwatch.com/investing/stock/cvx",
      "https://markets.ft.com/data/equities/tearsheet/summary?s=CVX:NYQ",
      "https://www.glassdoor.com/Overview/Working-at-Chevron-EI_IE13524.11,18.htm",
      "https://www.reuters.com/company/chevron-corp/",
      "https://www.weforum.org/organizations/chevron-corporation/",
      "https://www.theguardian.com/business/chevron",
      "https://www.morningstar.com/stocks/xnys/cvx/quote",
      "https://www.nasdaq.com/market-activity/stocks/cvx",
      "https://my.jobstreet.com/companies/chevron-168554240598187",
      "https://www.statista.com/topics/5256/chevron/",
      "https://www.ebsco.com/research-starters/business-and-management/chevron-corporation",
      "https://www.google.com/finance/quote/CVX:NYSE?hl=en",
      "https://chevronproductsuklim.outsystemsenterprise.com",
      "https://www.bloomberg.com/profile/company/7728792Z:MK",
      "https://www.yellowpages.my/-1228660"
    ],
    android_app_ids: [
      "com.Chevron.HES.EffeEngmt",
      "com.als.chevron",
      "com.chevron.StartWorkChecksIOGP",
      "com.chevron.cbpandroid",
      "com.chevron.retverify",
      "com.digitalinsight.cma.fiid01002",
      "com.mysalesforce.mycommunity.C00D3000000017zqEAA.A0OT5Y00000000jcWAA",
      "com.outsystemsenterprise.chevronproductsuklim.FASTOnboard",
      "com.outsystemsenterprise.chevronproductsuklim.MLDRMobile",
      "com.polarislabs.horizon.lubewatch.android"
    ],
    _processed: true
  },
  {
    name: "CocaCola",
    reasons: ["BDS_GRASS"],
    ws: ["https://www.cocacola.com", "https://www.coca-cola.com"],
    li: ["https://www.linkedin.com/company/the-coca-cola-company", "https://www.linkedin.com/showcase/cokesolutions"],
    fb: ["https://www.facebook.com/TheCocaColaCo", "https://www.facebook.com/CocaColaDeutschland"],
    tw: [
      "https://x.com/cocacola",
      "https://x.com/CocaColaRacing",
      "https://x.com/Cocacola_GH",
      "https://x.com/cocacola_ca",
      "https://x.com/COCACOLA_KSA",
      "https://x.com/cocacola_uy",
      "https://x.com/CocaCola_es",
      "https://x.com/cocacola_at",
      "https://x.com/acomercon",
      "https://x.com/rufino_cocacola",
      "https://x.com/cocacolaguitar",
      "https://x.com/CocaColaVe"
    ],
    ig: [
      "https://www.instagram.com/cocacola",
      "https://www.instagram.com/cocacola_uzbekistan/",
      "https://www.instagram.com/cocacola_kaz/",
      "https://www.instagram.com/cocacola_br/",
      "https://www.instagram.com/cocacolaarena/",
      "https://www.instagram.com/classicchristmasofficial/",
      "https://www.instagram.com/cocacolaar/",
      "https://www.instagram.com/cocacola.tj/",
      "https://www.instagram.com/cocacolapuertorico/",
      "https://www.instagram.com/cocacolafemsa_br/",
      "https://www.instagram.com/cocacolaicecekkariyer/",
      "https://www.instagram.com/mi_smo_cocacolahbcsrbija/",
      "https://www.instagram.com/cocacolape/",
      "https://www.instagram.com/cocacola_kenya/",
      "https://www.instagram.com/cocacola_tr/",
      "https://www.instagram.com/cocacola_kyrgyzstan/",
      "https://www.instagram.com/cocacola_id/",
      "https://www.instagram.com/cocacolave/"
    ],
    ytp: [
      "https://www.youtube.com/@Coca-Cola",
      "https://www.youtube.com/@Coca-Cola-Deutschland",
      "https://www.youtube.com/@Coca-Cola-offical",
      "https://www.youtube.com/@CocaColaArena",
      "https://www.youtube.com/@CocaColaAust",
      "https://www.youtube.com/@CocaColaHungary",
      "https://www.youtube.com/@CocaColaMaroc100",
      "https://www.youtube.com/@CocaColaNigeria",
      "https://www.youtube.com/@CocaColaPakistan",
      "https://www.youtube.com/@CocaColaPhilippinesOfficial",
      "https://www.youtube.com/@CocaColaThailand",
      "https://www.youtube.com/@CocaCola_Korea",
      "https://www.youtube.com/@CokeStudioPH",
      "https://www.youtube.com/@TheCoca-ColaCompany",
      "https://www.youtube.com/@cchbc",
      "https://www.youtube.com/@coca-coladz9301",
      "https://www.youtube.com/@coca-colaeuropacificpartners",
      "https://www.youtube.com/@coca-colakazakhstan6879",
      "https://www.youtube.com/@coca-colasouthafrica",
      "https://www.youtube.com/@cocacolaafrica",
      "https://www.youtube.com/@cocacolacl",
      "https://www.youtube.com/@cocacolacompanyuk",
      "https://www.youtube.com/@cocacolaegypt",
      "https://www.youtube.com/@cocacolamusicexperience",
      "https://www.youtube.com/@cocacolastudio4519",
      "https://www.youtube.com/@cokestudioindia",
      "https://www.youtube.com/@openhappiness",
      "https://www.youtube.com/@swirecoca-colausa6473",
      "https://www.youtube.com/@worldofcocacola"
    ],
    tt: [
      "https://www.tiktok.com/@cocacola",
      "https://www.tiktok.com/@cocacola_femsa",
      "https://www.tiktok.com/@cocacola_flow",
      "https://www.tiktok.com/@cocacola_japan",
      "https://www.tiktok.com/@cocacolaarena_ae",
      "https://www.tiktok.com/@cocacolateam6",
      "https://www.tiktok.com/@cocacolavn",
      "https://www.tiktok.com/@cokestudiopakistan"
    ],
    urls: ["https://nypost.com/tag/coca-cola", "https://www.theguardian.com/business/cocacola"],
    android_app_ids: ["com.greencopper.cocacolaflowfest", "com.mycoke.gulf", "mn.mcscocacola.coketohomemongolia"],
    _processed: true
  },
  {
    name: "Dell",
    reasons: ["BDS_PRIO"],
    ws: ["https://www.dell.com", "https://mlink-dell.com"],
    li: [
      "https://www.linkedin.com/company/alienware",
      "https://www.linkedin.com/company/credant-technologies",
      "https://www.linkedin.com/company/dell-compellent",
      "https://www.linkedin.com/company/delltechnologies",
      "https://www.linkedin.com/company/emc-corporation",
      "https://www.linkedin.com/company/gale-technologies",
      "https://www.linkedin.com/company/virtustream",
      "https://www.linkedin.com/company/xtremio",
      "https://www.linkedin.com/showcase/dell-tech-partner"
    ],
    fb: [
      "https://www.facebook.com/Dell",
      "https://www.facebook.com/DellRefurbished",
      "https://www.facebook.com/DellTechCareers",
      "https://www.facebook.com/DellTechnologies"
    ],
    ig: ["https://www.instagram.com/dell"],
    gh: ["https://github.com/dell"],
    ytp: [
      "https://www.youtube.com/@Dell",
      "https://www.youtube.com/@DellTWvlog",
      "https://www.youtube.com/@DellTechnologies",
      "https://www.youtube.com/@DellTechnologies-India",
      "https://www.youtube.com/@DellsuporteBrasil",
      "https://www.youtube.com/@TechSupportDell",
      "https://www.youtube.com/@dellnobrasil",
      "https://www.youtube.com/c/DellEnterpriseSupport"
    ],
    tt: ["https://www.tiktok.com/@dell"],
    th: ["https://www.threads.com/@dell"],
    urls: [
      "https://apps.apple.com/us/app/dell-ar-assistant/id1521610787",
      "https://apps.apple.com/us/app/dell-audio/id6472411862",
      "https://finance.yahoo.com/quote/DELL",
      "https://play.google.com/store/apps/developer?id=Dell+Inc.",
      "https://www.reddit.com/r/Dell"
    ],
    android_dev_id: "com.dell",
    android_app_ids: [
      "com.dell.PartnerProgram",
      "com.dell.ahapp",
      "com.dell.dellaudio",
      "com.dell.dfsm.mobile",
      "com.dell.omm",
      "com.emc.cloudiq",
      "com.emc.mobileapps.elabnavigator"
    ],
    _processed: true
  },
  {
    name: "Disney+",
    reasons: ["BDS_PRIO"],
    ws: ["https://www.disneyplus.com"],
    fb: [
      "https://www.facebook.com/DisneyCareers",
      "https://www.facebook.com/DisneyInArabic",
      "https://www.facebook.com/DisneyIsMyLifePage",
      "https://www.facebook.com/DisneyOnIceUK",
      "https://www.facebook.com/DisneyPlusDE",
      "https://www.facebook.com/DisneyPlusQuotes",
      "https://www.facebook.com/DisneyStoreDE",
      "https://www.facebook.com/disneymiddleast",
      "https://www.facebook.com/whatsondisneyplus"
    ],
    ig: ["https://www.instagram.com/disneyplus", "https://www.instagram.com/disneyplusuk"],
    ytp: [
      "https://www.youtube.com/@DisneyJuniorIT",
      "https://www.youtube.com/@DisneyPlusFR",
      "https://www.youtube.com/@DisneyPlusHK",
      "https://www.youtube.com/@DisneyPlusJP",
      "https://www.youtube.com/@DisneyPlusKR",
      "https://www.youtube.com/@DisneyPlusTR",
      "https://www.youtube.com/@DisneyPlusThailand",
      "https://www.youtube.com/@WhatsOnDisneyPlus",
      "https://www.youtube.com/@disneyplus",
      "https://www.youtube.com/@disneyplus-uk",
      "https://www.youtube.com/@disneyplus_indonesia",
      "https://www.youtube.com/@disneyplusbr",
      "https://www.youtube.com/@disneypluses",
      "https://www.youtube.com/@disneypluseu5125",
      "https://www.youtube.com/@disneyplusla",
      "https://www.youtube.com/@disneyplussg",
      "https://www.youtube.com/@disneyplustw9861",
      "https://www.youtube.com/@unofficialdisneyplusstarasia",
      "https://www.youtube.com/disneyplusmy",
      "https://www.youtube.com/disneyplusph"
    ],
    tt: [
      "https://www.tiktok.com/@disney",
      "https://www.tiktok.com/@disney.plus_x",
      "https://www.tiktok.com/@disneychannelplus",
      "https://www.tiktok.com/@disneyde",
      "https://www.tiktok.com/@disneyjr",
      "https://www.tiktok.com/@disneylat",
      "https://www.tiktok.com/@disneyplus",
      "https://www.tiktok.com/@disneyplus.tw",
      "https://www.tiktok.com/@disneyplusbr",
      "https://www.tiktok.com/@disneyplusde",
      "https://www.tiktok.com/@disneypluses",
      "https://www.tiktok.com/@disneyplusfr",
      "https://www.tiktok.com/@disneyplusid",
      "https://www.tiktok.com/@disneyplusit",
      "https://www.tiktok.com/@disneyplusjp",
      "https://www.tiktok.com/@disneypluskr",
      "https://www.tiktok.com/@disneyplusla",
      "https://www.tiktok.com/@disneyplusmy",
      "https://www.tiktok.com/@disneypluspeliculas",
      "https://www.tiktok.com/@disneyplusph",
      "https://www.tiktok.com/@disneyplusth",
      "https://www.tiktok.com/@disneyplustr",
      "https://www.tiktok.com/@disneyplusuk",
      "https://www.tiktok.com/@disneystudiosjp",
      "https://www.tiktok.com/@percyseries"
    ],
    urls: [
      "https://apps.apple.com/us/app/disney-magic-kingdoms/id731592936",
      "https://apps.apple.com/us/app/disney-store/id462423445",
      "https://apps.apple.com/us/app/disney/id1446075923",
      "https://apps.apple.com/us/app/disneyland/id1022164656",
      "https://apps.apple.com/us/app/my-disney-experience/id547436543"
    ],
    android_app_ids: [
      "com.disney.d23fanclub_goo",
      "com.disney.starwarshub_goo",
      "com.disney.teamofheroes.goo",
      "com.disney.wdpro.dlr",
      "com.disney.wdw.android",
      "in.startv.hotstar.dplus",
      "in.startv.hotstar.dplus.tv"
    ],
    _processed: true
  },
  {
    name: "DominosPizza",
    reasons: ["BDS_GRASS"],
    ws: ["https://www.dominos.com", "https://www.dominos.com.my"],
    fb: [
      "https://www.facebook.com/DominosMY",
      "https://www.facebook.com/Dominos/?brand_redir=165237120195992",
      "https://www.facebook.com/DominosPizzaPalestine"
    ],
    ig: [
      "https://www.instagram.com/dominos/?hl=en",
      "https://www.instagram.com/dominos",
      "https://www.instagram.com/dominos.sv",
      "https://www.instagram.com/dominos_id",
      "https://www.instagram.com/dominos_india",
      "https://www.instagram.com/dominos_pk",
      "https://www.instagram.com/dominos_vzla",
      "https://www.instagram.com/dominosbh",
      "https://www.instagram.com/dominosecuador",
      "https://www.instagram.com/dominosegypt",
      "https://www.instagram.com/dominosksa",
      "https://www.instagram.com/dominoslebanon",
      "https://www.instagram.com/dominosmexico",
      "https://www.instagram.com/dominosng",
      "https://www.instagram.com/dominosoman",
      "https://www.instagram.com/dominospanama",
      "https://www.instagram.com/dominospizza.stm",
      "https://www.instagram.com/dominospizza_es",
      "https://www.instagram.com/dominospizza_uy",
      "https://www.instagram.com/dominospizzabrasil",
      "https://www.instagram.com/dominospizzasrilanka",
      "https://www.instagram.com/sorgundominos"
    ],
    gh: ["https://github.com/DominosPizzaMY", "https://github.com/DominosPizzaThailand"],
    ytp: [
      "https://www.youtube.com/@DominosIlioupolis",
      "https://www.youtube.com/@DominosPizzaFriscoTX-xe4xd",
      "https://www.youtube.com/@DominosPizzaHrvatska",
      "https://www.youtube.com/@DominosPizzaIndia",
      "https://www.youtube.com/@DominosPizzaSwitzerland",
      "https://www.youtube.com/@DominosSGTV",
      "https://www.youtube.com/@DominosUK",
      "https://www.youtube.com/@dominos",
      "https://www.youtube.com/@dominos_aruba",
      "https://www.youtube.com/@dominosoffers007",
      "https://www.youtube.com/@dominosph",
      "https://www.youtube.com/@dominospizza1425",
      "https://www.youtube.com/@dominospizza1590",
      "https://www.youtube.com/@dominospizza1803",
      "https://www.youtube.com/@dominospizza2012",
      "https://www.youtube.com/@dominospizza2175",
      "https://www.youtube.com/@dominospizza2710",
      "https://www.youtube.com/@dominospizza2761",
      "https://www.youtube.com/@dominospizza2838",
      "https://www.youtube.com/@dominospizza3116",
      "https://www.youtube.com/@dominospizza380",
      "https://www.youtube.com/@dominospizza5097",
      "https://www.youtube.com/@dominospizza5379",
      "https://www.youtube.com/@dominospizza5654",
      "https://www.youtube.com/@dominospizza594",
      "https://www.youtube.com/@dominospizza6283",
      "https://www.youtube.com/@dominospizza6364",
      "https://www.youtube.com/@dominospizza8140",
      "https://www.youtube.com/@dominospizza8170",
      "https://www.youtube.com/@dominospizza8533",
      "https://www.youtube.com/@dominospizza9628",
      "https://www.youtube.com/@dominospizzabangladesh2453",
      "https://www.youtube.com/@dominospizzaca",
      "https://www.youtube.com/@dominospizzaczechrepublic7132",
      "https://www.youtube.com/@dominospizzadumastx9629",
      "https://www.youtube.com/@dominospizzageorgia9274",
      "https://www.youtube.com/@dominospizzajarrelltx9860",
      "https://www.youtube.com/@dominospizzalubbocktx9473",
      "https://www.youtube.com/@dominospizzamauritius7032",
      "https://www.youtube.com/@dominospizzapuertorico1516",
      "https://www.youtube.com/@dominospizzaua",
      "https://www.youtube.com/@dominospizzaunionmo3952",
      "https://www.youtube.com/@dompizzaindonesia"
    ],
    tt: [
      "https://www.tiktok.com/@dominos",
      "https://www.tiktok.com/@dominos.at",
      "https://www.tiktok.com/@dominos.pizza.arn",
      "https://www.tiktok.com/@dominos.pizza.denain",
      "https://www.tiktok.com/@dominos.pizza.wetteren",
      "https://www.tiktok.com/@dominos_az",
      "https://www.tiktok.com/@dominos_be",
      "https://www.tiktok.com/@dominos_id",
      "https://www.tiktok.com/@dominos_nl",
      "https://www.tiktok.com/@dominos_pizza_deinze",
      "https://www.tiktok.com/@dominos_pk",
      "https://www.tiktok.com/@dominos_vzla",
      "https://www.tiktok.com/@dominosby",
      "https://www.tiktok.com/@dominoscanada",
      "https://www.tiktok.com/@dominosguatemala",
      "https://www.tiktok.com/@dominoskuwait",
      "https://www.tiktok.com/@dominosnorge",
      "https://www.tiktok.com/@dominospizza_cl",
      "https://www.tiktok.com/@dominospizza_col",
      "https://www.tiktok.com/@dominospizza_es",
      "https://www.tiktok.com/@dominospizza_ng",
      "https://www.tiktok.com/@dominospizza_polska",
      "https://www.tiktok.com/@dominospizzaannecy",
      "https://www.tiktok.com/@dominospizzabd",
      "https://www.tiktok.com/@dominospizzabrasil",
      "https://www.tiktok.com/@dominospizzabunspa",
      "https://www.tiktok.com/@dominospizzafr",
      "https://www.tiktok.com/@dominospizzamalta",
      "https://www.tiktok.com/@dominospizzamauritius",
      "https://www.tiktok.com/@dominospizzaperu",
      "https://www.tiktok.com/@dominospizzaph",
      "https://www.tiktok.com/@dominospizzaromania",
      "https://www.tiktok.com/@dominospizzasoignies",
      "https://www.tiktok.com/@dominospizzass",
      "https://www.tiktok.com/@dominospizzathessaloniki",
      "https://www.tiktok.com/@dominospizzavietnam",
      "https://www.tiktok.com/@dominossg"
    ],
    th: [
      "https://www.threads.com/@dominos",
      "https://www.threads.com/@dominos_uk",
      "https://www.threads.com/@dominosmy"
    ],
    urls: [
      "https://www.foodpanda.my/chain/cb0hc/dominos-pizza",
      "https://apps.apple.com/us/app/dominos-canada/id621613017",
      "https://apps.apple.com/us/app/dominos-pizza-caribbean/id1117081050",
      "https://apps.apple.com/us/app/dominos-pizza-delivery-uk-roi/id426415753",
      "https://apps.apple.com/us/app/dominos-pizza-greece/id554503612",
      "https://apps.apple.com/us/app/dominos-pizza-usa/id436491861"
    ],
    android_app_ids: [
      "au.com.dominos.olo.android.app",
      "by.mc.dominos.com",
      "com.dominos.sa",
      "com.dominospizza.az",
      "uk.co.dominos.android"
    ],
    _processed: true
  },
  {
    name: "Expedia",
    reasons: ["BDS_PRESSURE"],
    ws: [
      "https://www.expedia.com",
      "https://expediagroup.com",
      "https://www.expedia.com.my",
      "https://www.expediapartnercentral.com"
    ],
    li: [
      "https://www.linkedin.com/company/expedia-cruises",
      "https://www.linkedin.com/company/expedia-cruises-flower-mound",
      "https://www.linkedin.com/company/expedia-cruises-sarasota-florida",
      "https://www.linkedin.com/company/expedia-ltd",
      "https://www.linkedin.com/company/expediagroup/posts",
      "https://www.linkedin.com/showcase/expedia",
      "https://www.linkedin.com/showcase/expedia-group-advertising",
      "https://www.linkedin.com/showcase/expedia-group-partnerships"
    ],
    fb: ["https://www.facebook.com/Expedia.de"],
    tw: [
      "https://x.com/Expedia",
      "https://x.com/ExpediaAsia",
      "https://x.com/ExpediaDE",
      "https://x.com/ExpediaGroup",
      "https://x.com/ExpediaHelp",
      "https://x.com/ExpediaUK",
      "https://x.com/expedia_au",
      "https://x.com/lifeatEG"
    ],
    ig: [
      "https://www.instagram.com/ecdalhousieaspen",
      "https://www.instagram.com/expedia",
      "https://www.instagram.com/expediaaholidays",
      "https://www.instagram.com/expediacruises",
      "https://www.instagram.com/expediacruisescharlotte",
      "https://www.instagram.com/expediacruisesduncan",
      "https://www.instagram.com/expediacruiseswestorlando",
      "https://www.instagram.com/expediade",
      "https://www.instagram.com/expediagroup",
      "https://www.instagram.com/expediamx",
      "https://www.instagram.com/expediaprotrav",
      "https://www.instagram.com/expediatrips",
      "https://www.instagram.com/expediaza_lps"
    ],
    ytp: [
      "https://www.youtube.com/@ExpediaCruisesFranchise",
      "https://www.youtube.com/@ExpediaGroupAdvertising",
      "https://www.youtube.com/@ExpediaInc",
      "https://www.youtube.com/@ExpediaJapan",
      "https://www.youtube.com/@ExpediaKorea",
      "https://www.youtube.com/@ExpediaNL",
      "https://www.youtube.com/@ExpediaSEA",
      "https://www.youtube.com/@ExpediaThailand_th",
      "https://www.youtube.com/@Expediacomau",
      "https://www.youtube.com/@ExpediaforProperties",
      "https://www.youtube.com/@eceastyork",
      "https://www.youtube.com/@expediaca",
      "https://www.youtube.com/@expediacroisieresamontreal8910",
      "https://www.youtube.com/@expediacruises2501",
      "https://www.youtube.com/@expediacruisesAZ",
      "https://www.youtube.com/@expediacruisesWA",
      "https://www.youtube.com/@expediacruisescentralalberta",
      "https://www.youtube.com/@expediacruisesinfrisco7733",
      "https://www.youtube.com/@expediacruisesmapleridge2322",
      "https://www.youtube.com/@expediacruisessherwoodpark7338",
      "https://www.youtube.com/@expediafrica",
      "https://www.youtube.com/@expediaindia677",
      "https://www.youtube.com/@expediauk",
      "https://www.youtube.com/user/Expedia/custom"
    ],
    tt: ["https://www.tiktok.com/@expedia"],
    th: [
      "https://www.threads.com/@expedia",
      "https://www.threads.com/@expediagroup",
      "https://www.threads.com/@expediajp",
      "https://www.threads.com/@expediamx"
    ],
    urls: [
      "https://apps.apple.com/us/app/expedia-hotels-flights-cars/id427916203",
      "https://chromewebstore.google.com/detail/expedia-price-scraper/hkohddkblmjfdhlkhnbjoaekkncagcno"
    ],
    android_app_ids: ["com.expedia.bookings", "com.expediapartnercentral"],
    _processed: true
  },
  {
    name: "ExpressVPN",
    ws: ["https://www.expressvpn.com"],
    reasons: ["f"],
    li: ["https://www.linkedin.com/company/expressvpn"],
    fb: ["https://www.facebook.com/ExpressVPN"],
    tw: [
      "https://x.com/2018ExpressVPN",
      "https://x.com/ExpressVPN_DE",
      "https://x.com/ExpressVPN_ES",
      "https://x.com/ExpressVPN_IT",
      "https://x.com/ExpressVPN_PT",
      "https://x.com/Us_Expressvpn",
      "https://x.com/expressvpn",
      "https://x.com/expressvpn_cn"
    ],
    ig: ["https://www.instagram.com/expressvpn"],
    gh: ["https://github.com/expressvpn"],
    ytp: ["https://www.youtube.com/@ExpressVPN", "https://www.youtube.com/@ExpressVPNStudios"],
    tt: ["https://www.tiktok.com/@expressvpn"],
    th: ["https://www.threads.com/@expressvpn"],
    urls: [
      "https://apps.apple.com/us/app/expresskeys-password-manager/id6748346556",
      "https://apps.apple.com/us/app/expressvpn-secure-fast-vpn/id886492891",
      "https://apps.apple.com/us/app/holiday-com/id6738407696",
      "https://apps.apple.com/us/developer/express-vpn/id1687252195",
      "https://chromewebstore.google.com/detail/expressvpn-%D1%80%D0%B0%D0%B1%D0%BE%D1%87%D0%B8%D0%B9-%D0%B2%D0%BF%D0%BD-%D0%B4%D0%BB/odgofcinnahbfjglcjkekbgoccgecklg",
      "https://chromewebstore.google.com/detail/expressvpn-keys-password/blgcbajigpdfohpgcmbbfnphcgifjopc",
      "https://chromewebstore.google.com/detail/expressvpn-vpn-proxy-for/fgddmllnllkalaagkghckoinaemmogpe"
    ],
    android_app_ids: ["com.expressvpn.vpn", "com.holiday.esim"],
    alt: [{ n: "BoycatVPN (1 Month free!)", ws: "https://boycat.io/vpn/order?via=theWall" }],
    _processed: true
  },
  {
    name: "HP",
    reasons: ["BDS_PRIO"],
    ws: [
      "https://www.hp.com",
      "https://www.omen.com",
      "https://www.hyperx.com",
      "https://www.hpe.com",
      "https://www.arubanetworks.com"
    ],
    li: [
      "https://www.linkedin.com/company/hewlett-packard-enterprise/",
      "https://www.linkedin.com/company/hyperx/",
      "https://www.linkedin.com/company/aruba-a-hewlett-packard-enterprise-company/",
      "https://www.linkedin.com/company/scytale.io/",
      "https://www.linkedin.com/showcase/hewlett-packard-labs/",
      "https://www.linkedin.com/showcase/hpe-financial-services/",
      "https://www.linkedin.com/showcase/hpe-partner-ready/",
      "https://www.linkedin.com/company/athonet/",
      "https://www.linkedin.com/company/cray-inc-/",
      "https://www.linkedin.com/showcase/hpe-it-solutions-for-smb/",
      "https://www.linkedin.com/showcase/hpe-servers-and-systems/",
      "https://www.linkedin.com/company/bluedata-software/",
      "https://www.linkedin.com/company/cloud-cruiser-inc/",
      "https://www.linkedin.com/company/nimble-storage/",
      "https://www.linkedin.com/company/cloudphysics/",
      "https://www.linkedin.com/company/axis-security/",
      "https://www.linkedin.com/company/determined-ai/",
      "https://www.linkedin.com/showcase/hpe-greenlake/",
      "https://www.linkedin.com/showcase/hpe-engage&grow-/",
      "https://www.linkedin.com/company/aruba-a-hewlett-packard-enterprise-company/",
      "https://www.linkedin.com/company/mapr-technologies/",
      "https://www.linkedin.com/company/simplivity-corporation/",
      "https://www.linkedin.com/company/cloud-technology-partners/",
      "https://www.linkedin.com/showcase/hpe-ai/",
      "https://www.linkedin.com/showcase/hpe-aruba-networking/",
      "https://www.linkedin.com/showcase/hpe-pointnext-services/",
      "https://www.linkedin.com/showcase/hpestorage/"
    ],
    fb: [
      "https://www.facebook.com/HP/",
      "https://www.facebook.com/OMENbyHP.de",
      "https://www.facebook.com/HyperXDE/?brand_redir=179848128697913"
    ],
    tw: [
      "https://x.com/hp",
      "https://x.com/OMENbyHP",
      "https://x.com/HyperX",
      "https://x.com/HPE",
      "https://x.com/HPE_Aruba_NETW"
    ]
  },
  {
    name: "Intel",
    reasons: ["BDS_PRIO"],
    ws: [
      "https://www.intel.com",
      "https://www.exploreintel.com",
      "https://www.intel.la",
      "https://www.intelcapital.com",
      "https://www.altera.com"
    ],
    li: [
      "https://www.linkedin.com/company/intel-corporation",
      "https://www.linkedin.com/company/intel-ignite",
      "https://www.linkedin.com/company/intel-labs",
      "https://www.linkedin.com/showcase/intel-business",
      "https://www.linkedin.com/showcase/intel-developer-zone",
      "https://www.linkedin.com/showcase/intel-developer",
      "https://www.linkedin.com/showcase/intel-foundry",
      "https://www.linkedin.com/showcase/intel-network-and-edge",
      "https://www.linkedin.com/showcase/intel-software",
      "https://www.linkedin.com/showcase/intelfabric",
      "https://www.linkedin.com/showcase/openatintel"
    ],
    fb: ["https://www.facebook.com/Intel"],
    tw: ["https://x.com/IntelSupport", "https://x.com/intel"],
    ig: ["https://www.instagram.com/intel", "https://www.instagram.com/inteluk"],
    gh: ["https://github.com/intel", "https://github.com/search?q=Intel&type=users"],
    ytp: [
      "https://www.youtube.com/@Intel",
      "https://www.youtube.com/@IntelFoundersTeam",
      "https://www.youtube.com/@IntelGraphics",
      "https://www.youtube.com/@IntelIndonesiaID",
      "https://www.youtube.com/@IntelIreland",
      "https://www.youtube.com/@IntelNewsroom",
      "https://www.youtube.com/@IntelSoftware",
      "https://www.youtube.com/@IntelTechnology",
      "https://www.youtube.com/@intelbusiness",
      "https://www.youtube.com/@intelindia",
      "https://www.youtube.com/@intelkorea",
      "https://www.youtube.com/@intelscope",
      "https://www.youtube.com/@intelthailand2902",
      "https://www.youtube.com/c/Intel"
    ],
    tt: ["https://www.tiktok.com/@intel", "https://www.tiktok.com/@intelgamingofficial"],
    urls: [
      "https://x.com/intel/affiliates",
      "https://play.google.com/store/apps/developer?id=Intel+Corporation",
      "https://edition.cnn.com/markets/stocks/INTC",
      "https://finance.yahoo.com/quote/INTC",
      "https://www.apple.com/us/search/Intel?src=globalnav",
      "https://www.cnbc.com/quotes/INTC",
      "https://www.forbes.com/companies/intel",
      "https://www.marketwatch.com/investing/stock/intc",
      "https://www.mida.gov.my/success-stories/intel-microelectronics",
      "https://www.pcmag.com/brands/intel",
      "https://www.reddit.com/r/intel",
      "https://www.reuters.com/company/intel-corp",
      "https://www.scmp.com/topics/intel",
      "https://www.tradingview.com/symbols/NASDAQ-INTC"
    ],
    android_dev_id: "com.intel",
    _processed: true
  },
  {
    name: "Jedyapps",
    reasons: ["h"],
    ws: ["https://www.jedyapps.com/"],
    li: ["https://www.linkedin.com/company/jedyapps"]
  },
  {
    name: "Kape Technologies",
    ws: ["https://www.kape.com"],
    reasons: ["f"],
    li: ["https://www.linkedin.com/company/kape-technologies"],
    gh: ["https://github.com/kapedata"],
    urls: [
      "https://www.instagram.com/explore",
      "https://www.kape.com",
      "https://www.reddit.com/r/Express_VPN/comments/pp6lwf/former_malware_distributor_kape_technologies_now",
      "https://x.com/search"
    ],
    _processed: true
  },
  {
    name: "McDonalds",
    reasons: ["BDS_GRASS"],
    ws: ["https://www.mcdonalds.com"],
    li: [
      "https://www.linkedin.com/company/mcdonald's-corporation",
      "https://www.linkedin.com/showcase/mccafe-canada",
      "https://www.linkedin.com/showcase/mcdonalds-france",
      "https://www.linkedin.com/company/mc-donald%27s-centre-de-l%27emploi-&-des-m%C3%A9tiers",
      "https://www.linkedin.com/showcase/mcdonald%27s-hungary",
      "https://www.linkedin.com/showcase/mcdonald's-azerbaijan"
    ],
    fb: [
      "https://www.facebook.com/McDonalds4200NBroadSt",
      "https://www.facebook.com/McDonalds4515PacificAve",
      "https://www.facebook.com/McDonalds6875SandlakeRd",
      "https://www.facebook.com/mcd"
    ],
    ig: [
      "https://www.instagram.com/mcdonalds",
      "https://www.instagram.com/mcdonalds_br",
      "https://www.instagram.com/mcdonalds_ve",
      "https://www.instagram.com/mcdonaldsbordeaux",
      "https://www.instagram.com/mcdonaldsbrunei",
      "https://www.instagram.com/mcdonaldscanada",
      "https://www.instagram.com/mcdonaldsde?fbclid=IwY2xjawPE9BxleHRuA2FlbQIxMABicmlkETFmb3VpanY4Yjl4MFR2QmhCc3J0YwZhcHBfaWQQMjIyMDM5MTc4ODIwMDg5MgABHg0s-23A0lssTO4bUrQRsbjU2uJ8FV9QgRNYgvDAn2vHmnI61V6QTBhqFy-I_aem_Ky40n63ekeKMJQ8DxoWrcQ",
      "https://www.instagram.com/mcdonaldsgers",
      "https://www.instagram.com/mcdonaldsid",
      "https://www.instagram.com/mcdonaldsjapan",
      "https://www.instagram.com/mcdonaldsksa",
      "https://www.instagram.com/mcdonaldsksa_ws",
      "https://www.instagram.com/mcdonaldsmagyarorszag",
      "https://www.instagram.com/mcdonaldsmalaysia",
      "https://www.instagram.com/mcdonaldsmx",
      "https://www.instagram.com/mcdonaldsoman",
      "https://www.instagram.com/mcdonaldspakistan",
      "https://www.instagram.com/mcdonaldspr",
      "https://www.instagram.com/mcdonaldsuk"
    ],
    ytp: [
      "https://www.youtube.com/@GTMcDonalds",
      "https://www.youtube.com/@McDonalds",
      "https://www.youtube.com/@McDonaldsAT",
      "https://www.youtube.com/@McDonaldsBrunei",
      "https://www.youtube.com/@McDonaldsColombiaa",
      "https://www.youtube.com/@McDonaldsDanmark",
      "https://www.youtube.com/@McDonaldsID",
      "https://www.youtube.com/@McDonaldsIndiaOfficial",
      "https://www.youtube.com/@McDonaldsItalia",
      "https://www.youtube.com/@McDonaldsJordanOfficial",
      "https://www.youtube.com/@McDonaldsMagyarorszag",
      "https://www.youtube.com/@McDonaldsNederland1",
      "https://www.youtube.com/@McDonaldsPakistanOfficial",
      "https://www.youtube.com/@McDonaldsPoland",
      "https://www.youtube.com/@McDonaldsSpain",
      "https://www.youtube.com/@McDonaldsTR",
      "https://www.youtube.com/@McDonaldsUAE",
      "https://www.youtube.com/@McDonaldsVE",
      "https://www.youtube.com/@mcdonalds6443",
      "https://www.youtube.com/@mcdonaldsPH",
      "https://www.youtube.com/@mcdonalds_br",
      "https://www.youtube.com/@mcdonaldscorp",
      "https://www.youtube.com/@mcdonaldsczech",
      "https://www.youtube.com/@mcdonaldsde",
      "https://www.youtube.com/@mcdonaldsegy",
      "https://www.youtube.com/@mcdonaldsgreece6193",
      "https://www.youtube.com/@mcdonaldshrvatska",
      "https://www.youtube.com/@mcdonaldsmalta7862",
      "https://www.youtube.com/@mcdonaldsportugal",
      "https://www.youtube.com/@mcdonaldsse",
      "https://www.youtube.com/@mcdonaldsslovenija6387",
      "https://www.youtube.com/@mcdonaldsswitzerland",
      "https://www.youtube.com/@mcdonaldthai",
      "https://www.youtube.com/@scottfamilymcdonalds2865",
      "https://www.youtube.com/@whatsupmcdonalds"
    ],
    tt: [
      "https://www.tiktok.com/@ligue1",
      "https://www.tiktok.com/@mccafeksa",
      "https://www.tiktok.com/@mcdmalaysia",
      "https://www.tiktok.com/@mcdo.balaruc",
      "https://www.tiktok.com/@mcdobreizh",
      "https://www.tiktok.com/@mcdomaroc",
      "https://www.tiktok.com/@mcdonalds",
      "https://www.tiktok.com/@mcdonalds.544",
      "https://www.tiktok.com/@mcdonalds.arg",
      "https://www.tiktok.com/@mcdonalds.kitchen",
      "https://www.tiktok.com/@mcdonalds5235",
      "https://www.tiktok.com/@mcdonalds_br",
      "https://www.tiktok.com/@mcdonalds_corp",
      "https://www.tiktok.com/@mcdonalds_es",
      "https://www.tiktok.com/@mcdonalds_nc",
      "https://www.tiktok.com/@mcdonalds_panama",
      "https://www.tiktok.com/@mcdonalds_polska",
      "https://www.tiktok.com/@mcdonalds_uy",
      "https://www.tiktok.com/@mcdonalds_ve",
      "https://www.tiktok.com/@mcdonaldsau",
      "https://www.tiktok.com/@mcdonaldsaustria",
      "https://www.tiktok.com/@mcdonaldsbehindscenes",
      "https://www.tiktok.com/@mcdonaldscanada",
      "https://www.tiktok.com/@mcdonaldscol",
      "https://www.tiktok.com/@mcdonaldsdallas",
      "https://www.tiktok.com/@mcdonaldsde",
      "https://www.tiktok.com/@mcdonaldsecu",
      "https://www.tiktok.com/@mcdonaldsegypt",
      "https://www.tiktok.com/@mcdonaldsfrance",
      "https://www.tiktok.com/@mcdonaldsid",
      "https://www.tiktok.com/@mcdonaldsitalia",
      "https://www.tiktok.com/@mcdonaldsjapan",
      "https://www.tiktok.com/@mcdonaldsjordan",
      "https://www.tiktok.com/@mcdonaldsksa",
      "https://www.tiktok.com/@mcdonaldsksa_ws",
      "https://www.tiktok.com/@mcdonaldskuwait",
      "https://www.tiktok.com/@mcdonaldsmx",
      "https://www.tiktok.com/@mcdonaldsnewengland",
      "https://www.tiktok.com/@mcdonaldsnl",
      "https://www.tiktok.com/@mcdonaldsnz",
      "https://www.tiktok.com/@mcdonaldsparis",
      "https://www.tiktok.com/@mcdonaldsperu",
      "https://www.tiktok.com/@mcdonaldspy",
      "https://www.tiktok.com/@mcdonaldsqatar",
      "https://www.tiktok.com/@mcdonaldsslovenija",
      "https://www.tiktok.com/@mcdonaldssuriname",
      "https://www.tiktok.com/@mcdonaldssverige",
      "https://www.tiktok.com/@mcdonaldsthai",
      "https://www.tiktok.com/@mcdonaldsturkiye",
      "https://www.tiktok.com/@mcdonaldsuae",
      "https://www.tiktok.com/@mcdonaldsuk",
      "https://www.tiktok.com/@mcdonaldsukraine",
      "https://www.tiktok.com/@mcdonaldsza",
      "https://www.tiktok.com/search/user?q=McDonalds"
    ],
    urls: [
      "https://apps.apple.com/us/app/mcdonalds-offers-and-delivery/id1114009187",
      "https://apps.apple.com/us/app/mcdonalds/id1217507712",
      "https://apps.apple.com/us/app/mcdonalds/id922103212",
      "https://play.google.com/store/apps/developer?id=McDonald%27s",
      "https://play.google.com/store/apps/developer?id=McDonald%27s+Apps",
      "https://www.ecosia.org/search?q=McDonalds",
      "https://www.facebook.com/profile.php?id=100089424621960",
      "https://www.facebook.com/profile.php?id=100089700018410",
      "https://www.facebook.com/profile.php?id=100089702111147",
      "https://www.facebook.com/profile.php?id=100089784610157",
      "https://www.facebook.com/profile.php?id=100090244985548",
      "https://www.facebook.com/profile.php?id=61585298593730",
      "https://www.facebook.com/profile.php?id=61585600799267",
      "https://www.instagram.com/explore/search/keyword/?q=McDonalds",
      "https://www.linkedin.com/notifications/?filter=all",
      "https://www.threads.com/@cat_vlog365/post/DMe1OmqPf2M"
    ],
    android_app_ids: [
      "com.brightstarr.mcdonaldsmcd",
      "com.mcdonalds.eventhub",
      "com.usekimono.android.mcd",
      "jp.co.mcdonalds.android",
      "ph.mobext.mcdelivery"
    ],
    _processed: true
  },
  {
    name: "PapaJohns",
    reasons: ["BDS_GRASS"],
    ws: ["https://www.papajohns.com"],
    li: ["https://www.linkedin.com/company/papajohns"],
    fb: [
      "https://www.facebook.com/PapaJohnsDE",
      "https://www.facebook.com/papajohns.com.my",
      "https://www.facebook.com/PapaJohnsEgypt",
      "https://www.facebook.com/PapaJohnsJordan"
    ],
    tw: ["https://x.com/PapaJohnsMsia"],
    ig: [
      "https://www.instagram.com/papajohns",
      "https://www.instagram.com/azpapajohns",
      "https://www.instagram.com/papa_johns_aricanorte",
      "https://www.instagram.com/papa_johns_bostanli",
      "https://www.instagram.com/papajohns",
      "https://www.instagram.com/papajohns.kz",
      "https://www.instagram.com/papajohnsbahrain",
      "https://www.instagram.com/papajohnschile",
      "https://www.instagram.com/papajohnsec",
      "https://www.instagram.com/papajohnshn",
      "https://www.instagram.com/papajohnspanama",
      "https://www.instagram.com/papajohnsperu",
      "https://www.instagram.com/papajohnspk",
      "https://www.instagram.com/papajohnsrd",
      "https://www.instagram.com/papajohnsuk"
    ],
    ytp: [
      "https://www.youtube.com/user/papajohns",
      "https://www.youtube.com/@PapaJohns-Bulgaria",
      "https://www.youtube.com/@PapaJohnsHonduras",
      "https://www.youtube.com/@PapaJohnsPizza-j4v",
      "https://www.youtube.com/@PapaJohnsRD",
      "https://www.youtube.com/@PapaJohns_IN",
      "https://www.youtube.com/@PapaJohns_PT",
      "https://www.youtube.com/@Yourpapajohns",
      "https://www.youtube.com/@papa-jm3bb",
      "https://www.youtube.com/@papajhonscoupons",
      "https://www.youtube.com/@papajohns",
      "https://www.youtube.com/@papajohns_ecuador",
      "https://www.youtube.com/@papajohnsbahrain2560",
      "https://www.youtube.com/@papajohnscdmx6338",
      "https://www.youtube.com/@papajohnscolumbus5904",
      "https://www.youtube.com/@papajohnserdington3328",
      "https://www.youtube.com/@papajohnsinternationalmark5182",
      "https://www.youtube.com/@papajohnsofcentralohio1877",
      "https://www.youtube.com/@papajohnsoman9439",
      "https://www.youtube.com/@papajohnspizza4131",
      "https://www.youtube.com/@papajohnspizzacambodia734",
      "https://www.youtube.com/@papajohnspizzacanada4484",
      "https://www.youtube.com/@papajohnspizzaegypt6795",
      "https://www.youtube.com/@papajohnspizzakuwait9096",
      "https://www.youtube.com/@papajohnsqatar5038",
      "https://www.youtube.com/@papajohnsseattle1154",
      "https://www.youtube.com/@papajohnsuk"
    ],
    tt: [
      "https://www.tiktok.com/@papajohns?lang=en",
      "https://www.tiktok.com/@azpapajohns",
      "https://www.tiktok.com/@papajohns.chile",
      "https://www.tiktok.com/@papajohns.kz",
      "https://www.tiktok.com/@papajohns.pk",
      "https://www.tiktok.com/@papajohns_es",
      "https://www.tiktok.com/@papajohns_rd",
      "https://www.tiktok.com/@papajohnscolombia",
      "https://www.tiktok.com/@papajohnscr",
      "https://www.tiktok.com/@papajohnsec",
      "https://www.tiktok.com/@papajohnsegy",
      "https://www.tiktok.com/@papajohnsgt",
      "https://www.tiktok.com/@papajohnshn",
      "https://www.tiktok.com/@papajohnsisrael",
      "https://www.tiktok.com/@papajohnskuwait",
      "https://www.tiktok.com/@papajohnsmexico",
      "https://www.tiktok.com/@papajohnsperu",
      "https://www.tiktok.com/@papajohnsuae",
      "https://www.tiktok.com/@papajohnsukofficial",
      "https://www.tiktok.com/@pizza_papajohns"
    ],
    th: [
      "https://www.threads.com/@papajohns",
      "https://www.threads.com/@papajohnscr",
      "https://www.threads.com/@papajohnsgt",
      "https://www.threads.com/@papajohnshn",
      "https://www.threads.com/@papajohnspanama",
      "https://www.threads.com/@papajohnsperu",
      "https://www.threads.com/@papajohnspk",
      "https://www.threads.com/@papajohnsrd"
    ],
    urls: [
      "https://www.reddit.com/r/PapaJohns",
      "https://apps.apple.com/us/app/papa-johns-costa-rica/id1498519065",
      "https://apps.apple.com/us/app/papa-johns-drc/id6737806430",
      "https://apps.apple.com/us/app/papa-johns-pizza-delivery/id407517450",
      "https://apps.apple.com/us/app/papa-johns-pizza-guyana/id6477437286",
      "https://apps.apple.com/us/app/papa-johns-pizza-uae/id1473648026",
      ":"
    ],
    android_app_ids: [
      "com.papajohns.android",
      "uk.co.papajohns.ppjqg",
      "com.loyaltyplant.partner.papajohns",
      "com.loyaltyplant.partner.papajohnsaz",
      "com.loyaltyplant.partner.papajohnsdrc",
      "com.loyaltyplant.partner.papajohnsjordan",
      "com.loyaltyplant.partner.papajohnskenya",
      "com.papa.johns.pizza.app.india",
      "com.papa.johns.pizza.app.qa",
      "pj.av.ol"
    ],
    _processed: true
  },
  {
    name: "PizzaHut",
    reasons: ["BDS_GRASS"],
    ws: ["https://www.pizzahut.com", "https://www.pizzahut.com.my"],
    fb: ["https://www.facebook.com/pizzahut.de", "https://www.facebook.com/pizzahut"],
    ig: [
      "https://www.instagram.com/pizzahutmalaysia",
      "https://www.instagram.com/pizzahutsaudi",
      "https://www.instagram.com/pizzahut",
      "https://www.instagram.com/pizzahut.indonesia",
      "https://www.instagram.com/pizzahut_india",
      "https://www.instagram.com/pizzahutau",
      "https://www.instagram.com/pizzahutbrasil",
      "https://www.instagram.com/pizzahutbrunei",
      "https://www.instagram.com/pizzahutde",
      "https://www.instagram.com/pizzahutec",
      "https://www.instagram.com/pizzahuteg",
      "https://www.instagram.com/pizzahutfortaleza",
      "https://www.instagram.com/pizzahuthn",
      "https://www.instagram.com/pizzahutkuwait",
      "https://www.instagram.com/pizzahutlebanon",
      "https://www.instagram.com/pizzahutmalaysia",
      "https://www.instagram.com/pizzahutmn",
      "https://www.instagram.com/pizzahutpakistan",
      "https://www.instagram.com/pizzahutpy",
      "https://www.instagram.com/pizzahutrd",
      "https://www.instagram.com/pizzahutsl",
      "https://www.instagram.com/pizzahutvzla"
    ],
    gh: ["https://github.com/PizzaHut-CDAC-Project"],
    ytp: [
      "https://www.youtube.com/pizzahutmalaysia",
      "https://www.youtube.com/@Pizza.Hut.Legion",
      "https://www.youtube.com/@PizzaHut7585",
      "https://www.youtube.com/@PizzaHutBrasil",
      "https://www.youtube.com/@PizzaHutFrance",
      "https://www.youtube.com/@PizzaHutHK_Official",
      "https://www.youtube.com/@PizzaHutIN",
      "https://www.youtube.com/@PizzaHutIndonesia",
      "https://www.youtube.com/@PizzaHutMiddleEast",
      "https://www.youtube.com/@PizzaHutPR",
      "https://www.youtube.com/@PizzaHutPe",
      "https://www.youtube.com/@PizzaHutPhilippinesMakeItGreat",
      "https://www.youtube.com/@PizzaHutPolska",
      "https://www.youtube.com/@PizzaHutSG",
      "https://www.youtube.com/@PizzaHutWeb",
      "https://www.youtube.com/@PizzaHutanimation",
      "https://www.youtube.com/@enjoypizzahut",
      "https://www.youtube.com/@pizzahutbd7911",
      "https://www.youtube.com/@pizzahutcuracao3576",
      "https://www.youtube.com/@pizzahutcyprus1306",
      "https://www.youtube.com/@pizzahutjamaica4426",
      "https://www.youtube.com/@pizzahutkuwait",
      "https://www.youtube.com/@pizzahutluxembourg7188",
      "https://www.youtube.com/@pizzahutmagyarorszag",
      "https://www.youtube.com/@pizzahutmalaysia",
      "https://www.youtube.com/@pizzahutmalta7867",
      "https://www.youtube.com/@pizzahutmongolia2014",
      "https://www.youtube.com/@pizzahutsouthafrica",
      "https://www.youtube.com/@pizzahutsrilanka",
      "https://www.youtube.com/@pizzahuttw",
      "https://www.youtube.com/user/pizzahut"
    ],
    tt: [
      "https://www.tiktok.com/@pizza.hutttt1",
      "https://www.tiktok.com/@pizza_hut_japan",
      "https://www.tiktok.com/@pizzahut",
      "https://www.tiktok.com/@pizzahut.bd",
      "https://www.tiktok.com/@pizzahut.indonesia",
      "https://www.tiktok.com/@pizzahut.kh",
      "https://www.tiktok.com/@pizzahut_kr",
      "https://www.tiktok.com/@pizzahut_myanmar",
      "https://www.tiktok.com/@pizzahut_reynosayrb",
      "https://www.tiktok.com/@pizzahutau",
      "https://www.tiktok.com/@pizzahutcanada",
      "https://www.tiktok.com/@pizzahutcl",
      "https://www.tiktok.com/@pizzahutco",
      "https://www.tiktok.com/@pizzahutde",
      "https://www.tiktok.com/@pizzahutdeliver",
      "https://www.tiktok.com/@pizzahutec",
      "https://www.tiktok.com/@pizzahutgreece",
      "https://www.tiktok.com/@pizzahuthnd",
      "https://www.tiktok.com/@pizzahutkuwait",
      "https://www.tiktok.com/@pizzahutmexico",
      "https://www.tiktok.com/@pizzahutmn",
      "https://www.tiktok.com/@pizzahutmsia",
      "https://www.tiktok.com/@pizzahutnuithanh_danang",
      "https://www.tiktok.com/@pizzahutpak",
      "https://www.tiktok.com/@pizzahutphils",
      "https://www.tiktok.com/@pizzahutportugal",
      "https://www.tiktok.com/@pizzahutsg",
      "https://www.tiktok.com/@pizzahutsrilanka",
      "https://www.tiktok.com/@pizzahutsv",
      "https://www.tiktok.com/@pizzahutuae",
      "https://www.tiktok.com/@pizzahutuk"
    ],
    th: [
      "https://www.threads.com/@pizzahut",
      "https://www.threads.com/@pizzahut.hk",
      "https://www.threads.com/@pizzahut.kh",
      "https://www.threads.com/@pizzahut.taiwan",
      "https://www.threads.com/@pizzahutmalaysia",
      "https://www.threads.com/@pizzahutuk"
    ],
    urls: [
      "https://www.foodpanda.my/restaurant/ores/pizza-hut-mid-valley-megamall",
      "https://www.pavilion-kl.com/store/pizza-hut",
      "https://apps.apple.com/us/app/pizza-hut-delivery-takeout/id321560858",
      "https://apps.apple.com/us/app/pizza-hut-ksa-order-food-now/id1023749374",
      "https://apps.apple.com/us/app/pizza-hut-kwt-order-food-now/id1458074450",
      "https://apps.apple.com/us/app/pizza-hut-uae-order-food-now/id1147168061"
    ],
    android_app_ids: [
      "com.pizzahut.malaysia",
      "bn.com.pizzahut.OSPHB",
      "com.ph.egypt",
      "com.pizzahut.bhr",
      "com.pizzahut.jeddah",
      "com.pizzahut.ksa",
      "com.pizzahut.kuwait",
      "com.pizzahut.morocco",
      "com.pizzahut.ng",
      "com.pizzahut.phd",
      "com.pizzahut.qatar",
      "com.pizzahut.rsa",
      "com.pizzahut.thailand",
      "com.pizzahutapp",
      "com.pizzahutguyana.android",
      "com.yum.pizzahutsg",
      "net.bonee.pizzaHut",
      "se.leeroygroup.pizzahut"
    ],
    _processed: true
  },
  {
    name: "Puma",
    reasons: ["BDS_PRIO"],
    ws: ["https://www.puma.com"],
    li: ["https://www.linkedin.com/company/puma/"],
    fb: ["https://www.facebook.com/PumaGermany/"],
    tw: ["https://x.com/puma"]
  },
  {
    name: "RE/MAX",
    reasons: ["BDS_PRIO"],
    ws: ["https://www.remax.com", "https://www.remax.my"],
    fb: [
      "https://www.facebook.com/1st.choiceegypt",
      "https://www.facebook.com/EverestRealEstate",
      "https://www.facebook.com/REMAXNewZealand",
      "https://www.facebook.com/REMAXSuccessToowoomba",
      "https://www.facebook.com/RemaxGoldenHouse",
      "https://www.facebook.com/RemaxPrestigeCA",
      "https://www.facebook.com/RemaxResultsMorningside",
      "https://www.facebook.com/RemaxWA",
      "https://www.facebook.com/TheAddressRemax",
      "https://www.facebook.com/remax",
      "https://www.facebook.com/remax.mn",
      "https://www.facebook.com/remaxhubinmongolia",
      "https://www.facebook.com/remaxmyhq",
      "https://www.facebook.com/remaxportugal"
    ],
    ig: [
      "https://www.instagram.com/kibrisremaxplus2",
      "https://www.instagram.com/remax",
      "https://www.instagram.com/remax.kaya",
      "https://www.instagram.com/remax_oldenburg",
      "https://www.instagram.com/remaxbr",
      "https://www.instagram.com/remaxlitoral.arg",
      "https://www.instagram.com/remaxtitanium"
    ],
    ytp: [
      "https://www.youtube.com/@Belizerealestatesearchrcolon",
      "https://www.youtube.com/@REMAXAustralia",
      "https://www.youtube.com/@REMAXBannerRealEstate",
      "https://www.youtube.com/@REMAXPhilippines2012",
      "https://www.youtube.com/@REMAXRomania",
      "https://www.youtube.com/@RemaxPoland",
      "https://www.youtube.com/@RemaxTurkiye",
      "https://www.youtube.com/@remaxaddress3465",
      "https://www.youtube.com/@remaxbrasil",
      "https://www.youtube.com/@remaxdazzle5849",
      "https://www.youtube.com/@remaxitalia",
      "https://www.youtube.com/@remaxmidlandskzn",
      "https://www.youtube.com/@remaxmongolia8086",
      "https://www.youtube.com/@remaxnewsroom",
      "https://www.youtube.com/@remaxofsa",
      "https://www.youtube.com/@remaxonesa4110",
      "https://www.youtube.com/@remaxsingapore",
      "https://www.youtube.com/@remaxslovenia",
      "https://www.youtube.com/REMAX"
    ],
    tt: [
      "https://www.tiktok.com/@miss_yan_yan",
      "https://www.tiktok.com/@remax.100.michiana",
      "https://www.tiktok.com/@remax.canada",
      "https://www.tiktok.com/@remax.imperia",
      "https://www.tiktok.com/@remax.properties",
      "https://www.tiktok.com/@remax_10",
      "https://www.tiktok.com/@remaxevolutionbrasov",
      "https://www.tiktok.com/@remaxonroatan"
    ],
    urls: [
      "https://apps.apple.com/us/app/re-max-experience-home-search/id1566709401",
      "https://apps.apple.com/us/app/re-max-max-connect/id1546225772",
      "https://apps.apple.com/us/app/re-max-properties-lb/id6503909000",
      "https://chromewebstore.google.com/detail/mymax-by-remax-turkiye/ahbmggfpfglepifhpbebbgkapfegddpp"
    ],
    android_app_ids: [
      "com.allygent.remaxcenter",
      "com.gryphtech.globalreferralprod",
      "com.remax.ahappremax",
      "com.remax.myremax",
      "com.remax.remax_tripoli",
      "com.remax.stickersApp",
      "com.remax.university",
      "tenant.ourproperty.com.remaxTENANT"
    ],
    _processed: true
  },
  {
    name: "Reebok",
    reasons: ["BDS_PRIO"],
    ws: ["https://www.reebok.com", "https://www.reebok.eu", "https://reebok.abfrl.in"],
    fb: ["https://www.facebook.com/ReebokAustriaGermanySwitzerland", "https://www.facebook.com/Reebok"],
    ig: [
      "https://www.instagram.com/reebokargentina",
      "https://www.instagram.com/reebokclubsp",
      "https://www.instagram.com/reebokcolombia",
      "https://www.instagram.com/reebokcostarica",
      "https://www.instagram.com/reebokeurope",
      "https://www.instagram.com/reebokindia",
      "https://www.instagram.com/reebokindonesia",
      "https://www.instagram.com/reebokkorea",
      "https://www.instagram.com/reebokphilippines",
      "https://www.instagram.com/reeboktr"
    ],
    ytp: [
      "https://www.youtube.com/@ReeSport",
      "https://www.youtube.com/@Reebok",
      "https://www.youtube.com/@Reebok-SouthAfrica",
      "https://www.youtube.com/@ReebokIndia",
      "https://www.youtube.com/@ReebokIndonesiaOfficial",
      "https://www.youtube.com/@ReebokMalaysia",
      "https://www.youtube.com/@ReebokSingapore",
      "https://www.youtube.com/@ReebokThailand",
      "https://www.youtube.com/@ReebokUniverse1",
      "https://www.youtube.com/@ReebokVietnam",
      "https://www.youtube.com/@ReebokWork",
      "https://www.youtube.com/@reebokkorea4713",
      "https://www.youtube.com/@reebokphilippines9567",
      "https://www.youtube.com/@reebokrussia",
      "https://www.youtube.com/@reeboksouthafrica4423",
      "https://www.youtube.com/@reeboktaiwan7500",
      "https://www.youtube.com/@reebokukraine5769"
    ],
    tt: [
      "https://www.tiktok.com/@reebok",
      "https://www.tiktok.com/@reebok.indonesia",
      "https://www.tiktok.com/@reebok_music",
      "https://www.tiktok.com/@reebokbrandhouse",
      "https://www.tiktok.com/@reebokeu",
      "https://www.tiktok.com/@reebokmx",
      "https://www.tiktok.com/@reeboksouthafrica",
      "https://www.tiktok.com/@reebokwatchmalaysia"
    ],
    urls: ["https://apps.apple.com/us/app/reebok/id6740590880"],
    android_app_ids: [
      "co.vitalist.reebokconnect",
      "com.changyow.iconsole4th",
      "com.rfeinternational.app_rbk",
      "com.tru.connect"
    ],
    _processed: true
  },
  {
    name: "Sabra",
    reasons: ["BDS_PRIO"],
    ws: ["https://sabra.com/"],
    li: ["https://www.linkedin.com/company/sabra-dipping-company-llc/"],
    fb: ["https://www.facebook.com/Sabra/"],
    tw: ["https://x.com/Sabra"]
  },
  {
    name: "Siemens",
    reasons: ["BDS_PRIO"],
    ws: ["https://www.siemens.com", "https://www.siemens-stiftung.org"],
    li: [
      "https://www.linkedin.com/company/enlighted-inc",
      "https://www.linkedin.com/showcase/siemensinfrastructure",
      "https://www.linkedin.com/showcase/siemens-financial-services",
      "https://www.linkedin.com/showcase/siemens-research-and-innovation-ecosystem",
      "https://www.linkedin.com/showcase/mobase/",
      "https://www.linkedin.com/showcase/siemens-mobility",
      "https://www.linkedin.com/showcase/siemens-industry-",
      "https://www.linkedin.com/company/ecodomus/",
      "https://www.linkedin.com/company/siemens-healthineers",
      "https://www.linkedin.com/company/siemenssoftware",
      "https://www.linkedin.com/company/hacon",
      "https://www.linkedin.com/company/siemens-eda"
    ],
    fb: ["https://www.facebook.com/Siemens"],
    tw: ["https://x.com/Siemens"]
  },
  {
    name: "SodaStream",
    reasons: ["BDS_PRIO"],
    ws: ["https://www.sodastream.com"],
    fb: [
      "https://www.facebook.com/SodaDoma",
      "https://www.facebook.com/SodaStream",
      "https://www.facebook.com/SodaStream.France",
      "https://www.facebook.com/SodaStreamDeutschland",
      "https://www.facebook.com/SodaStreamMagyarorszag",
      "https://www.facebook.com/SodaStreamMalta",
      "https://www.facebook.com/SodaStreamNL",
      "https://www.facebook.com/SodaStreamNZ",
      "https://www.facebook.com/SodaStreamOesterreich",
      "https://www.facebook.com/SodastreamItalia",
      "https://www.facebook.com/Sodastreamuk",
      "https://www.facebook.com/sodadk",
      "https://www.facebook.com/sodastream.sg",
      "https://www.facebook.com/sodastream.ua"
    ],
    ig: [
      "https://www.instagram.com/sodastream",
      "https://www.instagram.com/sodastream_santiago_chile",
      "https://www.instagram.com/sodastreamarg",
      "https://www.instagram.com/sodastreambe",
      "https://www.instagram.com/sodastreambr",
      "https://www.instagram.com/sodastreamcz",
      "https://www.instagram.com/sodastreamde",
      "https://www.instagram.com/sodastreamnl",
      "https://www.instagram.com/sodastreampolska",
      "https://www.instagram.com/sodastreamportugal",
      "https://www.instagram.com/sodastreamsuomi",
      "https://www.instagram.com/sodastreamsverige"
    ],
    ytp: [
      "https://www.youtube.com/@SodaStream.Slovakia",
      "https://www.youtube.com/@SodaStreamDE",
      "https://www.youtube.com/@SodaStreamHungary",
      "https://www.youtube.com/@SodaStreamNZ",
      "https://www.youtube.com/@SodaStreamPL",
      "https://www.youtube.com/@SodaStreamSingapore",
      "https://www.youtube.com/@SodaStreamTaiwan",
      "https://www.youtube.com/@SodaStreamUK",
      "https://www.youtube.com/@SodastreamArgentina",
      "https://www.youtube.com/@SodastreamBelgie",
      "https://www.youtube.com/@SodastreamCanada",
      "https://www.youtube.com/@SodastreamFrance",
      "https://www.youtube.com/@sodastream",
      "https://www.youtube.com/@sodastream2187",
      "https://www.youtube.com/@sodastreamit",
      "https://www.youtube.com/@sodastreampoland4056",
      "https://www.youtube.com/@sodastreamportugal1243",
      "https://www.youtube.com/@sodastreamsingapore2930",
      "https://www.youtube.com/@sodastreamukie"
    ],
    tt: [
      "https://www.tiktok.com/@sodastream",
      "https://www.tiktok.com/@sodastream.benlux",
      "https://www.tiktok.com/@sodastream.es",
      "https://www.tiktok.com/@sodastream.france",
      "https://www.tiktok.com/@sodastream.magyarorszag",
      "https://www.tiktok.com/@sodastreamarg",
      "https://www.tiktok.com/@sodastreamau",
      "https://www.tiktok.com/@sodastreamcanada",
      "https://www.tiktok.com/@sodastreamdach",
      "https://www.tiktok.com/@sodastreamgermany",
      "https://www.tiktok.com/@sodastreamit",
      "https://www.tiktok.com/@sodastreamnordics",
      "https://www.tiktok.com/@sodastreamnz",
      "https://www.tiktok.com/@sodastreampolska",
      "https://www.tiktok.com/@sodastreamsg",
      "https://www.tiktok.com/@sodastreamuk"
    ],
    _processed: true
  },
  {
    name: "Texaco",
    reasons: ["BDS_PRIO"],
    ws: [
      "https://www.texaco.com",
      "https://starrewards.valero.com",
      "https://www.chevrontexacocards.com/Chevron",
      "https://www.texacoinhawaii.com"
    ],
    ig: ["https://www.instagram.com/texacolubricants/?hl=en"],
    ytp: [
      "https://www.youtube.com/@TexacoLubricantsTV",
      "https://www.youtube.com/@Texaco_Srbija",
      "https://www.youtube.com/@texacoinhawaii"
    ],
    tt: [
      "https://www.tiktok.com/@edsllanosdecalibio",
      "https://www.tiktok.com/@texaco.cienaguita",
      "https://www.tiktok.com/@texaco.k1165.sepa2",
      "https://www.tiktok.com/@texaco.peten",
      "https://www.tiktok.com/@texacocontechroncolombia",
      "https://www.tiktok.com/@texacoguatemala",
      "https://www.tiktok.com/@texacolaesmeralda",
      "https://www.tiktok.com/@texacolasamericas",
      "https://www.tiktok.com/@texacowithtechron"
    ],
    urls: [
      "https://apps.apple.com/us/app/texaco/id1451359429",
      "https://www.texacolubricants.com/en_uk/home/Our-People.html",
      "https://www.texacolubricants.com/en_uk/home/products/by_brand/delo.html?src-tab=products",
      "https://www.texacolubricants.com/en_uk/home/products/by_brand/havoline.html?src-tab=products",
      "https://www.texacolubricants.com/en_uk/home/products/by_brand/hdax.html?src-tab=products",
      "https://www.texacolubricants.com/en_uk/home/products/by_brand/techron.html?src-tab=products"
    ],
    android_app_ids: ["com.polarislabs.horizon.texacolubewatch.android"],
    _processed: true
  },
  { name: "Wixsite (hosting)", reasons: ["h"], ws: ["wixsite.com"], li: [""], fb: [""], tw: [""] },
  {
    name: "Wordtune",
    reasons: ["h"],
    ws: ["https://www.wordtune.com"],
    li: ["https://www.linkedin.com/showcase/wordtune"],
    fb: ["https://www.facebook.com/wordtune"],
    tw: ["https://x.com/wordtune"],
    ig: ["https://www.instagram.com/wordtune_official"],
    ytc: ["https://www.youtube.com/channel/UCDQlFKBK11jIxm4iVymoAtA"],
    tt: ["https://www.tiktok.com/@wordtune_official"],
    urls: [
      "https://chromewebstore.google.com/detail/wordtune-ai-paraphrasing/nllcnknpjnininklegdoijpljgdjkijc",
      "https://microsoftedge.microsoft.com/addons/detail/wordtune-ai-paraphrasing/fgngodlaekdlibajobmkaklibdggemdd",
      "https://www.linkedin.com/newsletters/6995001803318681600"
    ],
    _processed: true
  }
]
