import { ManualOverrideFields } from "../../types"

export type ManualAdditionItem = {
  name: string
} & (
  | ManualOverrideFields
  | { _processed: true }
  | (ManualOverrideFields & { _processed: true })
  | (ManualOverrideFields & { urls?: string[] })
  | (ManualOverrideFields & { _processed: true; urls?: string[] })
)

export const manualAdditions: ManualAdditionItem[] = [
  {
    name: "AHAV",
    reasons: ["b"],
    ws: ["https://www.ahava.com"],
    li: ["https://www.linkedin.com/company/dead-sea-laboratories-ahava"],
    fb: ["https://www.facebook.com/ahavagermany"],
    tw: [""]
  },
  {
    name: "AXA",
    reasons: ["b"],
    ws: ["https://www.axa.com", "https://www.axa.com.hk"],
    li: [
      "https://www.linkedin.com/company/axa/",
      "https://www.linkedin.com/company/axa-wealth/",
      "https://www.linkedin.com/company/axa-group-operations/",
      "https://www.linkedin.com/company/axa-partners/",
      "https://www.linkedin.com/company/axa-global-re/",
      "https://www.linkedin.com/company/bharti-axa-life-insurance/",
      "https://www.linkedin.com/company/axa-mbask-ojsc/",
      "https://www.linkedin.com/company/axa-investment-managers/",
      "https://www.linkedin.com/company/axa-life-invest/",
      "https://www.linkedin.com/company/architas-multi-manager/",
      "https://www.linkedin.com/company/axa-global-direct/",
      "https://www.linkedin.com/company/axa-uk/",
      "https://www.linkedin.com/showcase/healthanea/",
      "https://www.linkedin.com/showcase/axa-von-herz-zu-herz-e-v/",
      "https://www.linkedin.com/company/axahealth/",
      "https://www.linkedin.com/company/gig-saudi/",
      "https://www.linkedin.com/company/axahongkong/",
      "https://www.linkedin.com/company/axa-corporate-solutions/",
      "https://www.linkedin.com/company/axa-gulf/",
      "https://www.linkedin.com/company/axa-liabilities-managers/",
      "https://www.linkedin.com/company/axa-mps/",
      "https://www.linkedin.com/company/axa-minmetals-assurance/",
      "https://www.linkedin.com/company/axa-france/",
      "https://www.linkedin.com/showcase/axa-research-fund/"
    ],
    fb: [
      "https://www.facebook.com/AXA.de/",
      "https://www.facebook.com/AXAAssuranceMaroc",
      "https://www.facebook.com/axainsurance",
      "https://www.facebook.com/AXAHongKong"
    ],
    tw: ["https://x.com/AXA"],
    ig: [
      "https://www.instagram.com/axa",
      "https://www.instagram.com/axa_global",
      "https://www.instagram.com/axa_egypt",
      "https://www.instagram.com/axahealth",
      "https://www.instagram.com/axa_uk"
    ],
    ytp: [
      "https://www.youtube.com/@AXA",
      "https://www.youtube.com/@AXAIRL",
      "https://www.youtube.com/@AXAGBS",
      "https://www.youtube.com/@AXAHongKongVideos",
      "https://www.youtube.com/@axauk",
      "https://www.youtube.com/@AXAPHofficial",
      "https://www.youtube.com/@AXANICoUK",
      "https://www.youtube.com/@AXAHealth"
    ],
    tt: ["https://www.tiktok.com/@axa.com/"],
    th: ["https://www.threads.com/@axa.com/"],
    android_dev_id: "com.axa",
    android_app_ids: [
      "de.axa.noa",
      "com.rise_world.axa",
      "com.agh.ipmi.prod",
      "com.axaassistance.cardmemberbenefits",
      "ch.swisscharge.axa.sc",
      "com.axabanque.fr"
    ]
  },
  {
    name: "Caltex",
    reasons: ["b"],
    ws: ["https://www.caltex.com", "https://caltexlubricants.com"],
    fb: ["https://www.facebook.com/CaltexLubricantsEG", "https://www.facebook.com/CaltexSingapore"],
    tw: ["https://x.com/CaltexSingapore"],
    ig: ["https://www.instagram.com/boycottcaltex"],
    ytp: [
      "https://www.youtube.com/@CaltexBrand",
      "https://www.youtube.com/@CaltexDavao",
      "https://www.youtube.com/@CaltexLubricantsIN",
      "https://www.youtube.com/@CaltexNZ",
      "https://www.youtube.com/@CaltexPakistanOfficial",
      "https://www.youtube.com/@CaltexPronPiyananOil",
      "https://www.youtube.com/@CaltexSriLanka2021",
      "https://www.youtube.com/@Pt.lancarsaktioffice",
      "https://www.youtube.com/@caltex7410",
      "https://www.youtube.com/@caltex_australia",
      "https://www.youtube.com/@caltexbrafordlubricants5906",
      "https://www.youtube.com/@caltexcambodia1379",
      "https://www.youtube.com/@caltexcambodia1971",
      "https://www.youtube.com/@caltexcareers1480",
      "https://www.youtube.com/@caltexdigital7354",
      "https://www.youtube.com/@caltexeasterncape6866",
      "https://www.youtube.com/@caltexglenashley333",
      "https://www.youtube.com/@caltexksa1253",
      "https://www.youtube.com/@caltexlubenar4660",
      "https://www.youtube.com/@caltexlubricantsme",
      "https://www.youtube.com/@caltexnz2571",
      "https://www.youtube.com/@caltexnz5716",
      "https://www.youtube.com/@caltexofficialstoremalaysi5917",
      "https://www.youtube.com/@caltexsouthafrica5590"
    ],
    tt: [
      "https://www.tiktok.com/@caltex.tmn.intan",
      "https://www.tiktok.com/@caltex_emstar",
      "https://www.tiktok.com/@caltexassamkumbang",
      "https://www.tiktok.com/@caltexbachok",
      "https://www.tiktok.com/@caltexmy",
      "https://www.tiktok.com/@caltexsungaitong",
      "https://www.tiktok.com/@caltexthailand",
      "https://www.tiktok.com/@gimtit168"
    ],
    urls: [
      "https://apps.apple.com/us/app/caltex-nz/id1435121311",
      "https://apps.apple.com/us/app/caltex-pakistan/id1239372998",
      "https://apps.apple.com/us/app/caltex-workshop/id1522862138",
      "https://apps.apple.com/us/app/caltexgo-rewards/id1607535654",
      "https://apps.apple.com/us/app/netlube-caltex-australia/id685230181",
      "https://apps.apple.com/us/app/netlube-caltex-new-zealand/id946248618",
      "https://play.google.com/store/apps/developer?id=Chevron+Singapore+Pte+Ltd",
      "https://afsc.org/BoycottChevron"
    ],
    android_app_ids: [
      "com.Caltex.CaltexWorkshop",
      "com.caltex.starcardonline",
      "com.chevron.caltexgo.prod",
      "pk.caltex.chevron"
    ],
    _processed: true
  },
  {
    name: "Carrefour",
    reasons: ["b"],
    ws: ["https://www.carrefour.com"],
    fb: [
      "https://www.facebook.com/Carrefour.Iraq",
      "https://www.facebook.com/CarrefourGeorgia",
      "https://www.facebook.com/Carrefoursaudi",
      "https://www.facebook.com/carrefour",
      "https://www.facebook.com/carrefouregypt"
    ],
    ig: [
      "https://www.instagram.com/carrefoures",
      "https://www.instagram.com/carrefourfrance",
      "https://www.instagram.com/carrefoursa"
    ],
    gh: ["https://github.com/Carrefour-Group"],
    ytp: [
      "https://www.youtube.com/@C4TVShow",
      "https://www.youtube.com/@CarrefourBE",
      "https://www.youtube.com/@CarrefourEgypt1",
      "https://www.youtube.com/@CarrefourFrance",
      "https://www.youtube.com/@CarrefourItaliaOfficial",
      "https://www.youtube.com/@CarrefourPL",
      "https://www.youtube.com/@CarrefourRomania",
      "https://www.youtube.com/@CarrefourUAE",
      "https://www.youtube.com/@GrupoCarrefourBrasil",
      "https://www.youtube.com/@carrefour",
      "https://www.youtube.com/@carrefour_israel",
      "https://www.youtube.com/@carrefourargentina",
      "https://www.youtube.com/@carrefourbrasil",
      "https://www.youtube.com/@carrefourcuracao",
      "https://www.youtube.com/@carrefourpakistan9493",
      "https://www.youtube.com/@carrefouruganda",
      "https://www.youtube.com/c/CarrefourTunisiehypermarch%C3%A9"
    ],
    tt: [
      "https://www.tiktok.com/@carrefour.egypt",
      "https://www.tiktok.com/@carrefour.israel",
      "https://www.tiktok.com/@carrefour.laval0",
      "https://www.tiktok.com/@carrefour.maurice",
      "https://www.tiktok.com/@carrefour_chalon_sud",
      "https://www.tiktok.com/@carrefour_polynesie",
      "https://www.tiktok.com/@carrefour_rosnysousbois",
      "https://www.tiktok.com/@carrefourargentina",
      "https://www.tiktok.com/@carrefourbh",
      "https://www.tiktok.com/@carrefourbrasil",
      "https://www.tiktok.com/@carrefourci",
      "https://www.tiktok.com/@carrefourfortresswaly",
      "https://www.tiktok.com/@carrefourfrance",
      "https://www.tiktok.com/@carrefourmaroc",
      "https://www.tiktok.com/@carrefourpakistan",
      "https://www.tiktok.com/@carrefourromania",
      "https://www.tiktok.com/@carrefoursakurumsal",
      "https://www.tiktok.com/@carrefoursaudi",
      "https://www.tiktok.com/@carrefourtaiwan",
      "https://www.tiktok.com/@carrefouruae",
      "https://www.tiktok.com/search/user?q=Carrefour"
    ],
    urls: [
      "https://apps.apple.com/us/app/carrefour-argentina/id6472512419",
      "https://apps.apple.com/us/app/carrefour-banco/id1488627762",
      "https://apps.apple.com/us/app/carrefour-destreland-contact/id1487957089",
      "https://apps.apple.com/us/app/carrefour-france/id378305156",
      "https://apps.apple.com/us/app/carrefour-maroc/id1644896168",
      "https://apps.apple.com/us/app/carrefour-martinique/id1436006846",
      "https://apps.apple.com/us/app/carrefour-r%C3%A9union/id1480709890",
      "https://apps.apple.com/us/app/carrefoursa-online-al%C4%B1%C5%9Fveri%C5%9F/id1460593315",
      "https://apps.apple.com/us/app/maf-carrefour-online-shopping/id626805470"
    ],
    android_app_ids: ["com.aswat.carrefouruae", "com.carrefourgu", "mn.io.carrefour"],
    _processed: true
  },
  {
    name: "Chevron",
    reasons: ["b"],
    ws: [
      "https://www.chevron.com",
      "https://www.chevronlubricants.com",
      "www.cpchem.com",
      "https://chevronfuels.com",
      "https://www.chevronmarineproducts.com"
    ],
    li: [
      "https://www.linkedin.com/showcase/chevron-marine-products",
      "https://www.linkedin.com/company/chevron",
      "https://www.linkedin.com/showcase/chevron-colorado",
      "https://www.linkedin.com/showcase/chevronaustralia",
      "https://www.linkedin.com/showcase/chevronhouston",
      "https://www.linkedin.com/showcase/global-lubricants",
      "https://www.linkedin.com/showcase/chevron-new-energies",
      "https://www.linkedin.com/showcase/chevron-delo",
      "https://www.linkedin.com/showcase/chevron-india",
      "https://www.linkedin.com/showcase/chevron-bangladesh",
      "https://www.linkedin.com/showcase/chevron-israel",
      "https://www.linkedin.com/showcase/chevron-oronite",
      "https://www.linkedin.com/showcase/chevron-marine-products",
      "https://www.linkedin.com/company/noble-energy",
      "https://www.linkedin.com/showcase/chevron-technology-ventures"
    ],
    fb: [
      "https://www.facebook.com/BonifaceChevronStation",
      "https://www.facebook.com/Chevron",
      "https://www.facebook.com/ChevronAdvocacyNetwork",
      "https://www.facebook.com/ChevronFuelsandRenewableSolutions"
    ],
    tw: ["https://x.com/Chevron"],
    ig: ["https://www.instagram.com/chevron"],
    gh: ["https://github.com/ChevronETC"],
    ytp: [
      "https://www.youtube.com/@Chevron",
      "https://www.youtube.com/@ChevronOronite",
      "https://www.youtube.com/@ChevronTVArchive",
      "https://www.youtube.com/@chevron.australia",
      "https://www.youtube.com/@chevronangola6961",
      "https://www.youtube.com/@chevronfederalcreditunion9683",
      "https://www.youtube.com/@chevronfuels",
      "https://www.youtube.com/@chevronlubricants7032",
      "https://www.youtube.com/@chevronmarineproducts",
      "https://www.youtube.com/@chevronpascagoularefinery7857",
      "https://www.youtube.com/@chevronmarineproducts"
    ],
    ytc: ["https://www.youtube.com/channel/UCG7MOSE5VUfvaZocYhyxi4w"],
    tt: ["https://www.tiktok.com/@chevron"],
    th: ["https://www.threads.com/@chevron"],
    urls: [
      "https://apps.apple.com/us/app/chevron/id1450978468",
      "https://chevronadvocacynetwork.com",
      "https://play.google.com/store/apps/dev?id=5536479555375186639",
      "https://www.ecosia.org/search?q=Chevron",
      "https://finance.yahoo.com/quote/CVX/",
      "https://www.cnbc.com/quotes/CVX",
      "https://www.forbes.com/companies/chevron/",
      "https://www.bnm.gov.my/-/chevron-malaysia-limited",
      "https://www.marketwatch.com/investing/stock/cvx",
      "https://markets.ft.com/data/equities/tearsheet/summary?s=CVX:NYQ",
      "https://www.glassdoor.com/Overview/Working-at-Chevron-EI_IE13524.11,18.htm",
      "https://www.reuters.com/company/chevron-corp/",
      "https://www.weforum.org/organizations/chevron-corporation/",
      "https://www.theguardian.com/business/chevron",
      "https://www.morningstar.com/stocks/xnys/cvx/quote",
      "https://www.nasdaq.com/market-activity/stocks/cvx",
      "https://my.jobstreet.com/companies/chevron-168554240598187",
      "https://www.statista.com/topics/5256/chevron/",
      "https://www.ebsco.com/research-starters/business-and-management/chevron-corporation",
      "https://www.google.com/finance/quote/CVX:NYSE?hl=en",
      "https://chevronproductsuklim.outsystemsenterprise.com",
      "https://www.bloomberg.com/profile/company/7728792Z:MK",
      "https://www.yellowpages.my/-1228660"
    ],
    android_app_ids: [
      "com.Chevron.HES.EffeEngmt",
      "com.als.chevron",
      "com.chevron.StartWorkChecksIOGP",
      "com.chevron.cbpandroid",
      "com.chevron.retverify",
      "com.digitalinsight.cma.fiid01002",
      "com.mysalesforce.mycommunity.C00D3000000017zqEAA.A0OT5Y00000000jcWAA",
      "com.outsystemsenterprise.chevronproductsuklim.FASTOnboard",
      "com.outsystemsenterprise.chevronproductsuklim.MLDRMobile",
      "com.polarislabs.horizon.lubewatch.android"
    ],
    _processed: true
  },
  {
    name: "Dell",
    reasons: ["b"],
    ws: ["https://www.dell.com", "https://mlink-dell.com"],
    li: [
      "https://www.linkedin.com/company/alienware",
      "https://www.linkedin.com/company/credant-technologies",
      "https://www.linkedin.com/company/dell-compellent",
      "https://www.linkedin.com/company/delltechnologies",
      "https://www.linkedin.com/company/emc-corporation",
      "https://www.linkedin.com/company/gale-technologies",
      "https://www.linkedin.com/company/virtustream",
      "https://www.linkedin.com/company/xtremio",
      "https://www.linkedin.com/showcase/dell-tech-partner"
    ],
    fb: [
      "https://www.facebook.com/Dell",
      "https://www.facebook.com/DellRefurbished",
      "https://www.facebook.com/DellTechCareers",
      "https://www.facebook.com/DellTechnologies"
    ],
    ig: ["https://www.instagram.com/dell"],
    gh: ["https://github.com/dell"],
    ytp: [
      "https://www.youtube.com/@Dell",
      "https://www.youtube.com/@DellTWvlog",
      "https://www.youtube.com/@DellTechnologies",
      "https://www.youtube.com/@DellTechnologies-India",
      "https://www.youtube.com/@DellsuporteBrasil",
      "https://www.youtube.com/@TechSupportDell",
      "https://www.youtube.com/@dellnobrasil",
      "https://www.youtube.com/c/DellEnterpriseSupport"
    ],
    tt: ["https://www.tiktok.com/@dell"],
    th: ["https://www.threads.com/@dell"],
    urls: [
      "https://apps.apple.com/us/app/dell-ar-assistant/id1521610787",
      "https://apps.apple.com/us/app/dell-audio/id6472411862",
      "https://finance.yahoo.com/quote/DELL",
      "https://play.google.com/store/apps/developer?id=Dell+Inc.",
      "https://www.reddit.com/r/Dell"
    ],
    android_dev_id: "com.dell",
    android_app_ids: [
      "com.dell.PartnerProgram",
      "com.dell.ahapp",
      "com.dell.dellaudio",
      "com.dell.dfsm.mobile",
      "com.dell.omm",
      "com.emc.cloudiq",
      "com.emc.mobileapps.elabnavigator"
    ],
    _processed: true
  },
  {
    name: "Disney+",
    reasons: ["b"],
    ws: ["https://www.disneyplus.com"],
    fb: [
      "https://www.facebook.com/DisneyCareers",
      "https://www.facebook.com/DisneyInArabic",
      "https://www.facebook.com/DisneyIsMyLifePage",
      "https://www.facebook.com/DisneyOnIceUK",
      "https://www.facebook.com/DisneyPlusDE",
      "https://www.facebook.com/DisneyPlusQuotes",
      "https://www.facebook.com/DisneyStoreDE",
      "https://www.facebook.com/disneymiddleast",
      "https://www.facebook.com/whatsondisneyplus"
    ],
    ig: ["https://www.instagram.com/disneyplus", "https://www.instagram.com/disneyplusuk"],
    ytp: [
      "https://www.youtube.com/@DisneyJuniorIT",
      "https://www.youtube.com/@DisneyPlusFR",
      "https://www.youtube.com/@DisneyPlusHK",
      "https://www.youtube.com/@DisneyPlusJP",
      "https://www.youtube.com/@DisneyPlusKR",
      "https://www.youtube.com/@DisneyPlusTR",
      "https://www.youtube.com/@DisneyPlusThailand",
      "https://www.youtube.com/@WhatsOnDisneyPlus",
      "https://www.youtube.com/@disneyplus",
      "https://www.youtube.com/@disneyplus-uk",
      "https://www.youtube.com/@disneyplus_indonesia",
      "https://www.youtube.com/@disneyplusbr",
      "https://www.youtube.com/@disneypluses",
      "https://www.youtube.com/@disneypluseu5125",
      "https://www.youtube.com/@disneyplusla",
      "https://www.youtube.com/@disneyplussg",
      "https://www.youtube.com/@disneyplustw9861",
      "https://www.youtube.com/@unofficialdisneyplusstarasia",
      "https://www.youtube.com/disneyplusmy",
      "https://www.youtube.com/disneyplusph"
    ],
    tt: [
      "https://www.tiktok.com/@disney",
      "https://www.tiktok.com/@disney.plus_x",
      "https://www.tiktok.com/@disneychannelplus",
      "https://www.tiktok.com/@disneyde",
      "https://www.tiktok.com/@disneyjr",
      "https://www.tiktok.com/@disneylat",
      "https://www.tiktok.com/@disneyplus",
      "https://www.tiktok.com/@disneyplus.tw",
      "https://www.tiktok.com/@disneyplusbr",
      "https://www.tiktok.com/@disneyplusde",
      "https://www.tiktok.com/@disneypluses",
      "https://www.tiktok.com/@disneyplusfr",
      "https://www.tiktok.com/@disneyplusid",
      "https://www.tiktok.com/@disneyplusit",
      "https://www.tiktok.com/@disneyplusjp",
      "https://www.tiktok.com/@disneypluskr",
      "https://www.tiktok.com/@disneyplusla",
      "https://www.tiktok.com/@disneyplusmy",
      "https://www.tiktok.com/@disneypluspeliculas",
      "https://www.tiktok.com/@disneyplusph",
      "https://www.tiktok.com/@disneyplusth",
      "https://www.tiktok.com/@disneyplustr",
      "https://www.tiktok.com/@disneyplusuk",
      "https://www.tiktok.com/@disneystudiosjp",
      "https://www.tiktok.com/@percyseries"
    ],
    urls: [
      "https://apps.apple.com/us/app/disney-magic-kingdoms/id731592936",
      "https://apps.apple.com/us/app/disney-store/id462423445",
      "https://apps.apple.com/us/app/disney/id1446075923",
      "https://apps.apple.com/us/app/disneyland/id1022164656",
      "https://apps.apple.com/us/app/my-disney-experience/id547436543"
    ],
    android_app_ids: [
      "com.disney.d23fanclub_goo",
      "com.disney.starwarshub_goo",
      "com.disney.teamofheroes.goo",
      "com.disney.wdpro.dlr",
      "com.disney.wdw.android",
      "in.startv.hotstar.dplus",
      "in.startv.hotstar.dplus.tv"
    ],
    _processed: true
  },
  {
    name: "HP",
    reasons: ["b"],
    ws: [
      "https://www.hp.com",
      "https://www.omen.com",
      "https://www.hyperx.com",
      "https://www.hpe.com",
      "https://www.arubanetworks.com"
    ],
    li: [
      "https://www.linkedin.com/company/hewlett-packard-enterprise/",
      "https://www.linkedin.com/company/hyperx/",
      "https://www.linkedin.com/company/aruba-a-hewlett-packard-enterprise-company/",
      "https://www.linkedin.com/company/scytale.io/",
      "https://www.linkedin.com/showcase/hewlett-packard-labs/",
      "https://www.linkedin.com/showcase/hpe-financial-services/",
      "https://www.linkedin.com/showcase/hpe-partner-ready/",
      "https://www.linkedin.com/company/athonet/",
      "https://www.linkedin.com/company/cray-inc-/",
      "https://www.linkedin.com/showcase/hpe-it-solutions-for-smb/",
      "https://www.linkedin.com/showcase/hpe-servers-and-systems/",
      "https://www.linkedin.com/company/bluedata-software/",
      "https://www.linkedin.com/company/cloud-cruiser-inc/",
      "https://www.linkedin.com/company/nimble-storage/",
      "https://www.linkedin.com/company/cloudphysics/",
      "https://www.linkedin.com/company/axis-security/",
      "https://www.linkedin.com/company/determined-ai/",
      "https://www.linkedin.com/showcase/hpe-greenlake/",
      "https://www.linkedin.com/showcase/hpe-engage&grow-/",
      "https://www.linkedin.com/company/aruba-a-hewlett-packard-enterprise-company/",
      "https://www.linkedin.com/company/mapr-technologies/",
      "https://www.linkedin.com/company/simplivity-corporation/",
      "https://www.linkedin.com/company/cloud-technology-partners/",
      "https://www.linkedin.com/showcase/hpe-ai/",
      "https://www.linkedin.com/showcase/hpe-aruba-networking/",
      "https://www.linkedin.com/showcase/hpe-pointnext-services/",
      "https://www.linkedin.com/showcase/hpestorage/"
    ],
    fb: [
      "https://www.facebook.com/HP/",
      "https://www.facebook.com/OMENbyHP.de",
      "https://www.facebook.com/HyperXDE/?brand_redir=179848128697913"
    ],
    tw: [
      "https://x.com/hp",
      "https://x.com/OMENbyHP",
      "https://x.com/HyperX",
      "https://x.com/HPE",
      "https://x.com/HPE_Aruba_NETW"
    ]
  },
  {
    name: "Intel",
    reasons: ["b"],
    ws: [
      "https://www.intel.com",
      "https://www.exploreintel.com",
      "https://www.intel.la",
      "https://www.intelcapital.com",
      "https://www.altera.com"
    ],
    li: [
      "https://www.linkedin.com/company/intel-corporation",
      "https://www.linkedin.com/company/intel-ignite",
      "https://www.linkedin.com/company/intel-labs",
      "https://www.linkedin.com/showcase/intel-business",
      "https://www.linkedin.com/showcase/intel-developer-zone",
      "https://www.linkedin.com/showcase/intel-developer",
      "https://www.linkedin.com/showcase/intel-foundry",
      "https://www.linkedin.com/showcase/intel-network-and-edge",
      "https://www.linkedin.com/showcase/intel-software",
      "https://www.linkedin.com/showcase/intelfabric",
      "https://www.linkedin.com/showcase/openatintel"
    ],
    fb: ["https://www.facebook.com/Intel"],
    tw: ["https://x.com/IntelSupport", "https://x.com/intel"],
    ig: ["https://www.instagram.com/intel", "https://www.instagram.com/inteluk"],
    gh: ["https://github.com/intel", "https://github.com/search?q=Intel&type=users"],
    ytp: [
      "https://www.youtube.com/@Intel",
      "https://www.youtube.com/@IntelFoundersTeam",
      "https://www.youtube.com/@IntelGraphics",
      "https://www.youtube.com/@IntelIndonesiaID",
      "https://www.youtube.com/@IntelIreland",
      "https://www.youtube.com/@IntelNewsroom",
      "https://www.youtube.com/@IntelSoftware",
      "https://www.youtube.com/@IntelTechnology",
      "https://www.youtube.com/@intelbusiness",
      "https://www.youtube.com/@intelindia",
      "https://www.youtube.com/@intelkorea",
      "https://www.youtube.com/@intelscope",
      "https://www.youtube.com/@intelthailand2902",
      "https://www.youtube.com/c/Intel"
    ],
    tt: ["https://www.tiktok.com/@intel", "https://www.tiktok.com/@intelgamingofficial"],
    urls: [
      "https://x.com/intel/affiliates",
      "https://play.google.com/store/apps/developer?id=Intel+Corporation",
      "https://edition.cnn.com/markets/stocks/INTC",
      "https://finance.yahoo.com/quote/INTC",
      "https://www.apple.com/us/search/Intel?src=globalnav",
      "https://www.cnbc.com/quotes/INTC",
      "https://www.forbes.com/companies/intel",
      "https://www.marketwatch.com/investing/stock/intc",
      "https://www.mida.gov.my/success-stories/intel-microelectronics",
      "https://www.pcmag.com/brands/intel",
      "https://www.reddit.com/r/intel",
      "https://www.reuters.com/company/intel-corp",
      "https://www.scmp.com/topics/intel",
      "https://www.tradingview.com/symbols/NASDAQ-INTC"
    ],
    android_dev_id: "com.intel",
    _processed: true
  },
  {
    name: "Jedyapps",
    reasons: ["h"],
    ws: ["https://www.jedyapps.com/"],
    li: ["https://www.linkedin.com/company/jedyapps"]
  },
  {
    name: "Microsoft",
    reasons: ["b"],
    ws: ["https://www.microsoft.com"],
    fb: [
      "https://www.facebook.com/MicrosoftAfrica",
      "https://www.facebook.com/MicrosoftDE",
      "https://www.facebook.com/MicrosoftLife",
      "https://www.facebook.com/microsoftresearch"
    ],
    gh: [
      "https://github.com/AzurePipelines",
      "https://github.com/Microsoft-OpenSource-Labs",
      "https://github.com/Microsoft-corp",
      "https://github.com/MicrosoftCopilot",
      "https://github.com/MicrosoftDocs",
      "https://github.com/MicrosoftEdge",
      "https://github.com/MicrosoftResearch",
      "https://github.com/MicrosoftStudentChapter",
      "https://github.com/OfficeDev",
      "https://github.com/azure-ai-foundry",
      "https://github.com/microsoft",
      "https://github.com/microsoftarchive",
      "https://github.com/microsoftgraph",
      "https://github.com/microsoftopensource",
      "https://github.com/search?q=Microsoft&type=users&p=2"
    ],
    ytp: [
      "https://www.youtube.com/@AzureDevelopers",
      "https://www.youtube.com/@EZANZ",
      "https://www.youtube.com/@MSFTEdge",
      "https://www.youtube.com/@MSFTMechanics",
      "https://www.youtube.com/@Microsoft",
      "https://www.youtube.com/@Microsoft.Copilot",
      "https://www.youtube.com/@Microsoft365Japan",
      "https://www.youtube.com/@MicrosoftAPAC",
      "https://www.youtube.com/@MicrosoftAzure",
      "https://www.youtube.com/@MicrosoftCommunityLearning",
      "https://www.youtube.com/@MicrosoftCustomerSupport",
      "https://www.youtube.com/@MicrosoftDeveloper",
      "https://www.youtube.com/@MicrosoftDynamics365",
      "https://www.youtube.com/@MicrosoftEDU",
      "https://www.youtube.com/@MicrosoftFabric",
      "https://www.youtube.com/@MicrosoftHoloLens",
      "https://www.youtube.com/@MicrosoftLearn",
      "https://www.youtube.com/@MicrosoftPowerApps",
      "https://www.youtube.com/@MicrosoftPowerBI",
      "https://www.youtube.com/@MicrosoftSecurity",
      "https://www.youtube.com/@MicrosoftSecurityCommunity",
      "https://www.youtube.com/@MicrosoftTaiwan",
      "https://www.youtube.com/@MicrosoftTeams",
      "https://www.youtube.com/@WorkingAtMicrosoft",
      "https://www.youtube.com/@events_msft",
      "https://www.youtube.com/@microsoftdesign",
      "https://www.youtube.com/@mspowerplatform",
      "https://www.youtube.com/user/officevideos/showcase",
      "https://www.youtube.com/user/surface/custom"
    ],
    tt: [
      "https://www.tiktok.com/@expertzone_na",
      "https://www.tiktok.com/@expertzoneitalia",
      "https://www.tiktok.com/@microsoft",
      "https://www.tiktok.com/@microsoft365",
      "https://www.tiktok.com/@microsoft_israel_rnd",
      "https://www.tiktok.com/@microsoft_jp",
      "https://www.tiktok.com/@microsoftbrasil",
      "https://www.tiktok.com/@microsoftcopilot",
      "https://www.tiktok.com/@microsoftdeveloper",
      "https://www.tiktok.com/@microsoftedge",
      "https://www.tiktok.com/@microsoftedu",
      "https://www.tiktok.com/@microsoftlatam",
      "https://www.tiktok.com/@microsoftshopping",
      "https://www.tiktok.com/@surface",
      "https://www.tiktok.com/@windows",
      "https://www.tiktok.com/search/user?q=Microsoft"
    ],
    urls: [
      "https://chromewebstore.google.com/detail/add-to-microsoft-to-do/loblkkbfciiklgoblkigehhghfjfjede",
      "https://chromewebstore.google.com/detail/microsoft-bing-homepage-s/ddojnmkongaimkdddgmcccldlfhokcfb",
      "https://chromewebstore.google.com/detail/microsoft-bing-search-wit/fbgcedjacmlbgleddnoacbnijgmiolem",
      "https://chromewebstore.google.com/detail/microsoft-single-sign-on/ppnbnpeolgkicgegkbkbjmhlideopiji",
      "https://play.google.com/store/apps/dev?id=6720847872553662727"
    ],
    android_dev_id: "com.microsoft",
    _processed: true
  },
  {
    name: "Puma",
    reasons: ["b"],
    ws: ["https://www.puma.com"],
    li: ["https://www.linkedin.com/company/puma/"],
    fb: ["https://www.facebook.com/PumaGermany/"],
    tw: ["https://x.com/puma"]
  },
  {
    name: "RE/MAX",
    reasons: ["b"],
    ws: ["https://www.remax.com", "https://www.remax.my"],
    fb: [
      "https://www.facebook.com/1st.choiceegypt",
      "https://www.facebook.com/EverestRealEstate",
      "https://www.facebook.com/REMAXNewZealand",
      "https://www.facebook.com/REMAXSuccessToowoomba",
      "https://www.facebook.com/RemaxGoldenHouse",
      "https://www.facebook.com/RemaxPrestigeCA",
      "https://www.facebook.com/RemaxResultsMorningside",
      "https://www.facebook.com/RemaxWA",
      "https://www.facebook.com/TheAddressRemax",
      "https://www.facebook.com/remax",
      "https://www.facebook.com/remax.mn",
      "https://www.facebook.com/remaxhubinmongolia",
      "https://www.facebook.com/remaxmyhq",
      "https://www.facebook.com/remaxportugal"
    ],
    ig: [
      "https://www.instagram.com/kibrisremaxplus2",
      "https://www.instagram.com/remax",
      "https://www.instagram.com/remax.kaya",
      "https://www.instagram.com/remax_oldenburg",
      "https://www.instagram.com/remaxbr",
      "https://www.instagram.com/remaxlitoral.arg",
      "https://www.instagram.com/remaxtitanium"
    ],
    ytp: [
      "https://www.youtube.com/@Belizerealestatesearchrcolon",
      "https://www.youtube.com/@REMAXAustralia",
      "https://www.youtube.com/@REMAXBannerRealEstate",
      "https://www.youtube.com/@REMAXPhilippines2012",
      "https://www.youtube.com/@REMAXRomania",
      "https://www.youtube.com/@RemaxPoland",
      "https://www.youtube.com/@RemaxTurkiye",
      "https://www.youtube.com/@remaxaddress3465",
      "https://www.youtube.com/@remaxbrasil",
      "https://www.youtube.com/@remaxdazzle5849",
      "https://www.youtube.com/@remaxitalia",
      "https://www.youtube.com/@remaxmidlandskzn",
      "https://www.youtube.com/@remaxmongolia8086",
      "https://www.youtube.com/@remaxnewsroom",
      "https://www.youtube.com/@remaxofsa",
      "https://www.youtube.com/@remaxonesa4110",
      "https://www.youtube.com/@remaxsingapore",
      "https://www.youtube.com/@remaxslovenia",
      "https://www.youtube.com/REMAX"
    ],
    tt: [
      "https://www.tiktok.com/@miss_yan_yan",
      "https://www.tiktok.com/@remax.100.michiana",
      "https://www.tiktok.com/@remax.canada",
      "https://www.tiktok.com/@remax.imperia",
      "https://www.tiktok.com/@remax.properties",
      "https://www.tiktok.com/@remax_10",
      "https://www.tiktok.com/@remaxevolutionbrasov",
      "https://www.tiktok.com/@remaxonroatan"
    ],
    urls: [
      "https://apps.apple.com/us/app/re-max-experience-home-search/id1566709401",
      "https://apps.apple.com/us/app/re-max-max-connect/id1546225772",
      "https://apps.apple.com/us/app/re-max-properties-lb/id6503909000",
      "https://chromewebstore.google.com/detail/mymax-by-remax-turkiye/ahbmggfpfglepifhpbebbgkapfegddpp"
    ],
    android_app_ids: [
      "com.allygent.remaxcenter",
      "com.gryphtech.globalreferralprod",
      "com.remax.ahappremax",
      "com.remax.myremax",
      "com.remax.remax_tripoli",
      "com.remax.stickersApp",
      "com.remax.university",
      "tenant.ourproperty.com.remaxTENANT"
    ],
    _processed: true
  },
  {
    name: "Reebok",
    reasons: ["b"],
    ws: ["https://www.reebok.com", "https://www.reebok.eu", "https://reebok.abfrl.in"],
    fb: ["https://www.facebook.com/ReebokAustriaGermanySwitzerland", "https://www.facebook.com/Reebok"],
    ig: [
      "https://www.instagram.com/reebokargentina",
      "https://www.instagram.com/reebokclubsp",
      "https://www.instagram.com/reebokcolombia",
      "https://www.instagram.com/reebokcostarica",
      "https://www.instagram.com/reebokeurope",
      "https://www.instagram.com/reebokindia",
      "https://www.instagram.com/reebokindonesia",
      "https://www.instagram.com/reebokkorea",
      "https://www.instagram.com/reebokphilippines",
      "https://www.instagram.com/reeboktr"
    ],
    ytp: [
      "https://www.youtube.com/@ReeSport",
      "https://www.youtube.com/@Reebok",
      "https://www.youtube.com/@Reebok-SouthAfrica",
      "https://www.youtube.com/@ReebokIndia",
      "https://www.youtube.com/@ReebokIndonesiaOfficial",
      "https://www.youtube.com/@ReebokMalaysia",
      "https://www.youtube.com/@ReebokSingapore",
      "https://www.youtube.com/@ReebokThailand",
      "https://www.youtube.com/@ReebokUniverse1",
      "https://www.youtube.com/@ReebokVietnam",
      "https://www.youtube.com/@ReebokWork",
      "https://www.youtube.com/@reebokkorea4713",
      "https://www.youtube.com/@reebokphilippines9567",
      "https://www.youtube.com/@reebokrussia",
      "https://www.youtube.com/@reeboksouthafrica4423",
      "https://www.youtube.com/@reeboktaiwan7500",
      "https://www.youtube.com/@reebokukraine5769"
    ],
    tt: [
      "https://www.tiktok.com/@reebok",
      "https://www.tiktok.com/@reebok.indonesia",
      "https://www.tiktok.com/@reebok_music",
      "https://www.tiktok.com/@reebokbrandhouse",
      "https://www.tiktok.com/@reebokeu",
      "https://www.tiktok.com/@reebokmx",
      "https://www.tiktok.com/@reeboksouthafrica",
      "https://www.tiktok.com/@reebokwatchmalaysia"
    ],
    urls: ["https://apps.apple.com/us/app/reebok/id6740590880"],
    android_app_ids: [
      "co.vitalist.reebokconnect",
      "com.changyow.iconsole4th",
      "com.rfeinternational.app_rbk",
      "com.tru.connect"
    ],
    _processed: true
  },
  {
    name: "Sabra",
    reasons: ["b"],
    ws: ["https://sabra.com/"],
    li: ["https://www.linkedin.com/company/sabra-dipping-company-llc/"],
    fb: ["https://www.facebook.com/Sabra/"],
    tw: ["https://x.com/Sabra"]
  },
  {
    name: "Siemens",
    reasons: ["b"],
    ws: ["https://www.siemens.com", "https://www.siemens-stiftung.org"],
    li: [
      "https://www.linkedin.com/company/enlighted-inc",
      "https://www.linkedin.com/showcase/siemensinfrastructure",
      "https://www.linkedin.com/showcase/siemens-financial-services",
      "https://www.linkedin.com/showcase/siemens-research-and-innovation-ecosystem",
      "https://www.linkedin.com/showcase/mobase/",
      "https://www.linkedin.com/showcase/siemens-mobility",
      "https://www.linkedin.com/showcase/siemens-industry-",
      "https://www.linkedin.com/company/ecodomus/",
      "https://www.linkedin.com/company/siemens-healthineers",
      "https://www.linkedin.com/company/siemenssoftware",
      "https://www.linkedin.com/company/hacon",
      "https://www.linkedin.com/company/siemens-eda"
    ],
    fb: ["https://www.facebook.com/Siemens"],
    tw: ["https://x.com/Siemens"]
  },
  {
    name: "SodaStream",
    reasons: ["b"],
    ws: ["https://www.sodastream.com"],
    fb: [
      "https://www.facebook.com/SodaDoma",
      "https://www.facebook.com/SodaStream",
      "https://www.facebook.com/SodaStream.France",
      "https://www.facebook.com/SodaStreamDeutschland",
      "https://www.facebook.com/SodaStreamMagyarorszag",
      "https://www.facebook.com/SodaStreamMalta",
      "https://www.facebook.com/SodaStreamNL",
      "https://www.facebook.com/SodaStreamNZ",
      "https://www.facebook.com/SodaStreamOesterreich",
      "https://www.facebook.com/SodastreamItalia",
      "https://www.facebook.com/Sodastreamuk",
      "https://www.facebook.com/sodadk",
      "https://www.facebook.com/sodastream.sg",
      "https://www.facebook.com/sodastream.ua"
    ],
    ig: [
      "https://www.instagram.com/sodastream",
      "https://www.instagram.com/sodastream_santiago_chile",
      "https://www.instagram.com/sodastreamarg",
      "https://www.instagram.com/sodastreambe",
      "https://www.instagram.com/sodastreambr",
      "https://www.instagram.com/sodastreamcz",
      "https://www.instagram.com/sodastreamde",
      "https://www.instagram.com/sodastreamnl",
      "https://www.instagram.com/sodastreampolska",
      "https://www.instagram.com/sodastreamportugal",
      "https://www.instagram.com/sodastreamsuomi",
      "https://www.instagram.com/sodastreamsverige"
    ],
    ytp: [
      "https://www.youtube.com/@SodaStream.Slovakia",
      "https://www.youtube.com/@SodaStreamDE",
      "https://www.youtube.com/@SodaStreamHungary",
      "https://www.youtube.com/@SodaStreamNZ",
      "https://www.youtube.com/@SodaStreamPL",
      "https://www.youtube.com/@SodaStreamSingapore",
      "https://www.youtube.com/@SodaStreamTaiwan",
      "https://www.youtube.com/@SodaStreamUK",
      "https://www.youtube.com/@SodastreamArgentina",
      "https://www.youtube.com/@SodastreamBelgie",
      "https://www.youtube.com/@SodastreamCanada",
      "https://www.youtube.com/@SodastreamFrance",
      "https://www.youtube.com/@sodastream",
      "https://www.youtube.com/@sodastream2187",
      "https://www.youtube.com/@sodastreamit",
      "https://www.youtube.com/@sodastreampoland4056",
      "https://www.youtube.com/@sodastreamportugal1243",
      "https://www.youtube.com/@sodastreamsingapore2930",
      "https://www.youtube.com/@sodastreamukie"
    ],
    tt: [
      "https://www.tiktok.com/@sodastream",
      "https://www.tiktok.com/@sodastream.benlux",
      "https://www.tiktok.com/@sodastream.es",
      "https://www.tiktok.com/@sodastream.france",
      "https://www.tiktok.com/@sodastream.magyarorszag",
      "https://www.tiktok.com/@sodastreamarg",
      "https://www.tiktok.com/@sodastreamau",
      "https://www.tiktok.com/@sodastreamcanada",
      "https://www.tiktok.com/@sodastreamdach",
      "https://www.tiktok.com/@sodastreamgermany",
      "https://www.tiktok.com/@sodastreamit",
      "https://www.tiktok.com/@sodastreamnordics",
      "https://www.tiktok.com/@sodastreamnz",
      "https://www.tiktok.com/@sodastreampolska",
      "https://www.tiktok.com/@sodastreamsg",
      "https://www.tiktok.com/@sodastreamuk"
    ],
    _processed: true
  },
  {
    name: "Texaco",
    reasons: ["b"],
    ws: [
      "https://www.texaco.com",
      "https://starrewards.valero.com",
      "https://www.chevrontexacocards.com/Chevron",
      "https://www.texacoinhawaii.com"
    ],
    ig: ["https://www.instagram.com/texacolubricants/?hl=en"],
    ytp: [
      "https://www.youtube.com/@TexacoLubricantsTV",
      "https://www.youtube.com/@Texaco_Srbija",
      "https://www.youtube.com/@texacoinhawaii"
    ],
    tt: [
      "https://www.tiktok.com/@edsllanosdecalibio",
      "https://www.tiktok.com/@texaco.cienaguita",
      "https://www.tiktok.com/@texaco.k1165.sepa2",
      "https://www.tiktok.com/@texaco.peten",
      "https://www.tiktok.com/@texacocontechroncolombia",
      "https://www.tiktok.com/@texacoguatemala",
      "https://www.tiktok.com/@texacolaesmeralda",
      "https://www.tiktok.com/@texacolasamericas",
      "https://www.tiktok.com/@texacowithtechron"
    ],
    urls: [
      "https://apps.apple.com/us/app/texaco/id1451359429",
      "https://www.texacolubricants.com/en_uk/home/Our-People.html",
      "https://www.texacolubricants.com/en_uk/home/products/by_brand/delo.html?src-tab=products",
      "https://www.texacolubricants.com/en_uk/home/products/by_brand/havoline.html?src-tab=products",
      "https://www.texacolubricants.com/en_uk/home/products/by_brand/hdax.html?src-tab=products",
      "https://www.texacolubricants.com/en_uk/home/products/by_brand/techron.html?src-tab=products"
    ],
    android_app_ids: ["com.polarislabs.horizon.texacolubewatch.android"],
    _processed: true
  },
  { name: "Wixsite (hosting)", reasons: ["h"], ws: ["wixsite.com"], li: [""], fb: [""], tw: [""] },
  {
    name: "Wordtune",
    reasons: ["h"],
    ws: ["https://www.wordtune.com"],
    li: ["https://www.linkedin.com/showcase/wordtune"],
    fb: ["https://www.facebook.com/wordtune"],
    tw: ["https://x.com/wordtune"],
    ig: ["https://www.instagram.com/wordtune_official"],
    ytc: ["https://www.youtube.com/channel/UCDQlFKBK11jIxm4iVymoAtA"],
    tt: ["https://www.tiktok.com/@wordtune_official"],
    urls: [
      "https://chromewebstore.google.com/detail/wordtune-ai-paraphrasing/nllcnknpjnininklegdoijpljgdjkijc",
      "https://microsoftedge.microsoft.com/addons/detail/wordtune-ai-paraphrasing/fgngodlaekdlibajobmkaklibdggemdd",
      "https://www.linkedin.com/newsletters/6995001803318681600"
    ],
    _processed: true
  }
]
