declare const styles: {
  readonly bgLayer: string
  readonly bgOverlay: string
  readonly combinedTitle: string
  readonly communitySection: string
  readonly contactButton: string
  readonly container: string
  readonly content: string
  readonly contentWrapper: string
  readonly donateButton: string
  readonly donateButtonRow: string
  readonly donationImage: string
  readonly donationImageLink: string
  readonly fadeInUp: string
  readonly featureSection: string
  readonly featureText: string
  readonly footer: string
  readonly footerActions: string
  readonly gradientShift: string
  readonly header: string
  readonly installDropSection: string
  readonly largeDonateButton: string
  readonly link: string
  readonly oneTimeButton: string
  readonly playIcon: string
  readonly playOverlay: string
  readonly pluginName: string
  readonly pulseGlow: string
  readonly reportButton: string
  readonly sectionTitle: string
  readonly shareButton: string
  readonly shareButtons: string
  readonly shareLabel: string
  readonly shareSection: string
  readonly shimmer: string
  readonly theWallLogo: string
  readonly title: string
  readonly urgentSection: string
  readonly version: string
  readonly versionContent: string
  readonly versionSection: string
  readonly versionText: string
  readonly videoCaption: string
  readonly videoThumbnail: string
  readonly videoThumbnailContainer: string
  readonly videoThumbnailLink: string
  readonly videoThumbnailWrapper: string
}
export = styles
